// French translations for destinations and hotels

export const locationsFR = [
  {
    id: "nairobi",
    name: "Nairobi",
    slug: "nairobi",
    description: "La capitale dynamique du Kenya – meilleurs hôtels de luxe, safaris au parc national de Nairobi, centre de girafes et expériences culturelles",
    image: "/Nairobi.avif",
    longDescription: "Nairobi, la capitale animée du Kenya et porte d'entrée principale des safaris d'Afrique de l'Est, combine l'énergie urbaine avec des expériences wildlife incroyables. Connue dans le monde entier comme la seule capitale avec un parc national en son sein, Nairobi offre des safaris au parc national de Nairobi à seulement 20 minutes du centre-ville. Visitez le célèbre Giraffe Centre, le musée Karen Blixen, le David's Sheldrick Elephant Orphanage, et le musée national de Nairobi. La ville abrite des hôtels de luxe, des lodges boutique, des restaurants sur les toits, une vie nocturne animée et d'excellents centres commerciaux.",
    attractions: ["Safari au parc national de Nairobi", "Giraffe Centre – Nourrir les girafes", "David Sheldrick Elephant & Rhino Orphanage", "Musée Karen Blixen (Out of Africa)", "Musée national de Nairobi", "Bomas of Kenya – Spectacle culturel", "Visites de Kibera Slum", "Nairobi Safari Walk", "Karura Forest – Randonnée"],
    bestTime: "Juin à octobre (saison sèche) et janvier à février",
    updatedAt: new Date(),
  },
  {
    id: "maasai-mara",
    name: "Maasai Mara",
    slug: "maasai-mara",
    description: "La Grande Migration, les Big Cats et les safaris en montgolfière – le parc national le plus célèbre du Kenya",
    image: "/maasai-mara.jpeg",
    longDescription: "Le Maasai Mara est la destination safari la plus emblématique du Kenya, mondialement connue pour la Grande Migration annuelle où plus de 1,5 million de gnous traversent les plannes de juillet à octobre. Le parc abrite une population dense de lions, léopards, guépards (les Big Cats), éléphants, girafes et zèbres. Les lodges de luxe offrent des vues sur les plannes infinies, et les safaris en montgolfière au lever du soleil sont une expérience inoubliable. La culture masaï authentique peut être vécue lors de visites de villages.",
    attractions: ["Grande Migration (juillet-octobre)", "Observation des lions et léopards", "Safari en montgolfière", "Visites de villages masaï", "Game drives au lever du soleil", "Migration des gnous et zèbres"],
    bestTime: "Juillet à octobre pour la migration, décembre à mars pour les naissances",
    updatedAt: new Date(),
  },
  {
    id: "amboseli",
    name: "Amboseli",
    slug: "amboseli",
    description: "Le royaume des éléphants avec le Kilimandjaro en arrière-plan – meilleur endroit pour voir des éléphants",
    image: "/amboseli.jpeg",
    longDescription: "Amboseli est mondialement connu pour ses vues imprenables sur le mont Kilimandjaro et ses grandes populations d'éléphants. Le parc offre некотор des meilleures opportunités de photographie wildlife au Kenya, avec des éléphants aux longues défenses marchant devant le glacier emblématiques du Kilimandjaro. Les zones marécageuses (swamps) attirent des centaines d'oiseaux et d'autres animaux, et les couchers de soleil sur le parc sont spectaculaires.",
    attractions: ["Vue sur le Kilimandjaro", "Observation des éléphants", "Photographie wildlife", "Observation des oiseaux", "Safari dans les marais", "Couchers de soleil spectaculaires"],
    bestTime: "Octobre à mars (vue la plus claire sur le Kilimandjaro)",
    updatedAt: new Date(),
  },
  {
    id: "tsavo-east",
    name: "Tsavo Est",
    slug: "tsavo-east",
    description: "Le plus grand parc national du Kenya avec ses éléphants rouges emblématiques",
    image: "/tsavo-east.jpg",
    longDescription: "Tsavo Est est le plus grand parc national du Kenya, célèbré pour ses élégants éléphants roux qui se baignent dans la poussière rouge caractéristique de la région. Le parc offre des safaris exclusifs loin des foules, avec des paysages variés allant des plaines arides aux collines rocheuses. La nourriture des lions sans crinière de Tsavo ajoute au mystère de cette région sauvage.",
    attractions: ["Éléphants rouges de Tsavo", "Lions sans crinière", "Safari exclusif", "Paysages variés", "Observation des oiseaux", "Lac mudd"],
    bestTime: "Octobre à mars (saison sèche)",
    updatedAt: new Date(),
  },
  {
    id: "tsavo-west",
    name: "Tsavo Ouest",
    slug: "tsavo-west",
    description: "Volcans, sources chaude et la célèbre Shetani Lava Flow",
    image: "/tsavo-west.jpg",
    longDescription: "Tsavo Ouest offre des paysages spectaculaires avec ses volcans, sources chaudes géothermiques et la célèbre coulée de lave Shetani. Le parc abrite une grande variété de faune incluant éléphants, lions, girafes et rhinocéros. Le lac Chala à la frontière tanzanienne offre des couchers de soleil magnifiques, et les grottes deMzima offrent une vue underwater sur les hippos.",
    attractions: ["Shetani Lava Flow", "Sources chaudes de Loch妇幼", "Volcans du parc", "Lac Chala", "Grottes de Mzima", "Rhinocéros"],
    bestTime: "Octobre à mars",
    updatedAt: new Date(),
  },
  {
    id: "samburu",
    name: "Samburu",
    slug: "samburu",
    description: "Le Special Five – guidée, zèbre de Grévy, autruche somali, oryx et gazelle de Beisa",
    image: "/samburu.jpg",
    longDescription: "Samburu dans le nord du Kenya offre une expérience safari unique avec son Special Five: la girafe reticulée, le zèbre de Grévy, l'autruche somali, l'oryx beisa et la gazelle de Beisa. Les paysages désertiques époustouflants et la culture samburu authentique complètent l'expérience. Les safaris sont plus exclusifs ici, avec moins de touristes que les parks du sud.",
    attractions: ["Special Five", "Culture samburu", "Paysages désertiques", "Safari exclusif", "Observation des oiseaux", "Rivière Ewaso Ng'iro"],
    bestTime: "Octobre à mars",
    updatedAt: new Date(),
  },
  {
    id: "nakuru",
    name: "Lac Nakuru",
    slug: "nakuru",
    description: "Des millions de flamants roses et sanctuaire de rhinocéros – parc national petit mais riche",
    image: "/lake-nakuru.jpg",
    longDescription: "Le parc national du lac Nakuru est célèbré pour ses millions de flamants roses qui créent un spectacle rose spectaculaire sur le lac alcalin. Le parc est aussi un sanctuaire important pour les rhinocéros noirs et blancs, avec l'une des meilleures populations du Kenya. Les paysages varient des bords du lac aux forêts de québé et aux falaises de狮子.",
    attractions: ["Flamants roses", "Sanctuaire rhinocéros", "Observation des oiseaux", "Forêts de sodio", "Babouins et singes", "Vue sur le Rift"],
    bestTime: "Octobre à mars (saison sèche)",
    updatedAt: new Date(),
  },
  {
    id: "naivasha",
    name: "Lac Naivasha",
    slug: "naivasha",
    description: "Bateaux, hippos et Crescent Island – escapade détente près de Nairobi",
    image: "/naivasha.jpg",
    longDescription: "Le lac Naivasha est l'un des lacs d'eau douce les plus beaux du Kenya, situé à seulement 90 minutes de Nairobi dans la vallée du Rift. Famous pour les safaris en bateau où vous pouvez vous approcher des hippos, des aigles pêcheurs et des centaines d'espèces d'oiseaux. Profitez du vélo et des game drives dans le parc national de Hell's Gate – le seul parc du Kenya où vous pouvez marcher ou faire du vélo parmi les zèbres, girafes et buffles.",
    attractions: ["Safari en bateau sur le lac", "Observation des hippos", "Hell's Gate – Vélo et randonnée", "Crescent Island – Safari à pied", "Crater Lake pour flamants", "Sources thermales"],
    bestTime: "Toute l'année",
    updatedAt: new Date(),
  },
  {
    id: "meru",
    name: "Meru",
    slug: "meru",
    description: "Wilderness intact – expérience safari authentique hors des sentiers battus",
    image: "/meru.jpg",
    longDescription: "Meru est l'une des regions safari les plus préservées du Kenya, offrant une expérience authentique loin du tourisme de masse. Le parc national de Meru abritait les derniers rhinocéros noirs du Kenya dans les années 80, et sa population a été restaurée. Les safari hors-piste sont autorisés, permettant des encounters wildlife exceptionnelles dans cette nature préservée.",
    attractions: ["Wilderness préservée", "Rhinocéros noirs", "Safari hors-piste", "Rivières et systèmes fluviaux", "Chasse photographique", "Expérience authentique"],
    bestTime: "Octobre à mars",
    updatedAt: new Date(),
  },
];

// Simple hotel data for demo - in production you'd have full translations
export const hotelsFR = [
  {
    id: "nairobi-001",
    name: "Fairmont The Norfolk",
    location: "Nairobi",
    price: 350,
    rating: 4.8,
    image: "/nairobi-1.jpg",
    description: "Hôtel légendaire de Nairobi avec elegance coloniale et standards modernes. Situé au cœur de la ville, parfait pour les voyages d'affaires et leisure.",
  },
  {
    id: "nairobi-002",
    name: "Serena Hotel Nairobi",
    location: "Nairobi",
    price: 280,
    rating: 4.6,
    image: "/nairobi-2.jpg",
    description: "Hôtel de luxe avec vue sur le parc national de Nairobi. Piscine, spa et restaurants gastronomiques.",
  },
  {
    id: "maasai-mara-001",
    name: "Mara Serena Safari Lodge",
    location: "Maasai Mara",
    price: 450,
    rating: 4.7,
    image: "/mara-1.jpg",
    description: "Lodge iconique avec vue sur la Grande Migration. Safari drives inclus, cuisine gourmet.",
  },
  {
    id: "maasai-mara-002",
    name: "Mara Intrepids Camp",
    location: "Maasai Mara",
    price: 380,
    rating: 4.5,
    image: "/mara-2.jpg",
    description: "Camp de luxe avec tentes spacieuses et terrace privée. Safari en vehicle 4x4.",
  },
  {
    id: "amboseli-001",
    name: "Tortilis Camp Amboseli",
    location: "Amboseli",
    price: 420,
    rating: 4.8,
    image: "/amboseli-1.jpg",
    description: "Camp de luxe avec vue directe sur le Kilimandjaro. Observation des éléphants depuis la piscine.",
  },
];

export const faqsFR = [
  { question: "Quelle est la meilleure période pour un safari au Kenya?", answer: "La meilleure période est de juin à octobre pour la saison sèche et la Grande Migration. Janvier à février est aussi excellent avec moins de monde." },
  { question: "Ai-je besoin d'un visa pour le Kenya?", answer: "Oui, un visa est requis. Vous pouvez obtenir un e-visa en ligne avant votre voyage sur le portail officiel du gouvernement kenyan." },
  { question: "Quel est le budget moyen pour un safari?", answer: "Un safari de luxe dure généralement 300-500 USD par personne et par jour, incluant hébergement, repas et safaris." },
  { question: "Le Kenya est-il sûr pour les touristes?", answer: "Le Kenya est généralement sûr pour les touristes dans les zones safari et touristiques. Nous recommandons de suivre les conseils de votre opérateurs." },
  { question: "Puis-je réservez mon safari dernière minute?", answer: "C'est possible mais recommandé de réserver 2-3 mois à l'avance pour garantissant la disponibilité, surtout pendant la haute saison." },
  { question: "Quels animaux puis-je voir au Kenya?", answer: "Le Kenya offre les Big Five (lion, léopard, éléphant, buffle, rhinocéros), la Grande Migration, des centaines d'espèces d'oiseaux et plus." },
  { question: "Les safaris sont-ils adaptés aux familles?", answer: "Oui, de nombreux lodges proposent des activités pour enfants et des safaris adaptés aux familles." },
  { question: "Dois-je apporter des médicaments contre le paludisme?", answer: "Certaines zones safari nécessitent une prophylaxie. Consultez votre médecin et votre opérateurs pour des conseils spécifiques." },
];