// Spanish translations for destinations, hotels and FAQs

export const locationsES = [
  {
    id: "nairobi",
    name: "Nairobi",
    slug: "nairobi",
    description: "La vibrante capital de Kenia – mejores hoteles de lujo, safaris en el Parque Nacional de Nairobi, Centro de Jirafas",
    image: "/Nairobi.avif",
    longDescription: "Nairobi, la capital animada de Kenia y puerta de entrada principal a los safaris del África Oriental, combina la energía urbana con experiencias de vida silvestre increíbles. Conocida worldwide como la única capital con un parque nacional dentro de sus límites, Nairobi ofrece safaris en el Parque Nacional de Nairobi a solo 20 minutos del centro. Visite el famoso Centro de Jirafas, el Museo Karen Blixen, el Orfanato de Elefantes David Sheldrick, y el Museo Nacional de Nairobi. La ciudad cuenta con hoteles de lujo, lodges boutique, restaurantes en azoteas y excelente compras.",
    attractions: ["Safari en Parque Nacional de Nairobi", "Centro de Jirafas – Alimentar jirafas", "Orfanato de Elefantes y Rinocerontes", "Museo Karen Blixen", "Museo Nacional de Nairobi", "Bomas de Kenia – Espectáculo cultural", "Visitas a Kibera Slum", "Nairobi Safari Walk", "Karura Forest – Senderismo"],
    bestTime: "Junio a octubre (temporada seca) y enero a febrero",
    updatedAt: new Date(),
  },
  {
    id: "maasai-mara",
    name: "Maasai Mara",
    slug: "maasai-mara",
    description: "La Gran Migración, los Big Cats y safaris en globo – el parque nacional más famoso de Kenia",
    image: "/maasai-mara.jpeg",
    longDescription: "Maasai Mara es el destino safari más emblemático de Kenia, mundialmente conocido por la Gran Migración anual donde más de 1,5 millones de ñus cruzan las llanuras de julio a octubre. El parque alberga una densa población de leones, leopardos, guepardos (Big Cats), elefantes, jirafas y cebras. Los lodges de lujo ofrecen vistas a las infinitas llanuras, y los safaris en globo al amanecer son una experiencia inolvidable. La cultura masai auténtica puede experimentarse en visitas a aldeas.",
    attractions: ["Gran Migración (julio-octubre)", "Avistamiento de leones y leopardos", "Safari en globo", "Visitas a aldeas masai", "Game drives al amanecer", "Migración de ñus y cebras"],
    bestTime: "Julio a octubre para la migración, diciembre a marzo para los nacimientos",
    updatedAt: new Date(),
  },
  {
    id: "amboseli",
    name: "Amboseli",
    slug: "amboseli",
    description: "El reino de los elefantes con el Kilimanjaro de fondo – mejor lugar para ver elefantes",
    image: "/amboseli.jpeg",
    longDescription: "Amboseli es mundialmente conocido por sus impresionantes vistas del monte Kilimanjaro y sus grandes poblaciones de elefantes. El parque ofrece algunas de las mejores oportunidades de fotografía de vida silvestre en Kenia, con elefantes con grandes colmillos caminando frente al glaciar icónico del Kilimanjaro. Los humedales atraen cientos de aves y otros animales, y los atardeceres son spectaculaires.",
    attractions: ["Vista del Kilimanjaro", "Avistamiento de elefantes", "Fotografía de vida silvestre", "Avistamiento de aves", "Safari en humedales", "Atardeceres espectaculares"],
    bestTime: "Octubre a marzo (vista más clara del Kilimanjaro)",
    updatedAt: new Date(),
  },
  {
    id: "tsavo-east",
    name: "Tsavo Este",
    slug: "tsavo-east",
    description: "El parque nacional más grande de Kenia con sus icónicos elefantes rojos",
    image: "/tsavo-east.jpg",
    longDescription: "Tsavo Este es el parque nacional más grande de Kenia, celebrado por sus elegantes elefantes rojizos que se bañan en el polvo rojo característico de la región. El parque ofrece safaris exclusivos lejos de las multitudes, con paisajes variados desde llanuras áridas hasta colinas rocosas. Los leones sin melena de Tsavo añaden al misterio de esta región salvaje.",
    attractions: ["Elefantes rojos de Tsavo", "Leones sin melena", "Safari exclusivo", "Paisajes variados", "Avistamiento de aves", "Lago Mud"],
    bestTime: "Octubre a marzo (temporada seca)",
    updatedAt: new Date(),
  },
  {
    id: "tsavo-west",
    name: "Tsavo Oeste",
    slug: "tsavo-west",
    description: "Volcanes, aguas termales y la famosa Shetani Lava Flow",
    image: "/tsavo-west.jpg",
    longDescription: "Tsavo Oeste ofrece paisajes espectaculares con sus volcanes, aguas termales geotérmicas y la famosa corriente de lava Shetani. El parque alberga una gran variedad de fauna incluyendo elefantes, leones, jirafas y rinocerontes. El lago Chala en la frontera tanzana ofrece atardeceres magníficos, y las cuevas de Mzima ofrecen vista bajo el agua de los hipopótamos.",
    attractions: ["Shetani Lava Flow", "Aguas termales", "Volcanes del parque", "Lago Chala", "Cuevas de Mzima", "Rinocerontes"],
    bestTime: "Octubre a marzo",
    updatedAt: new Date(),
  },
  {
    id: "samburu",
    name: "Samburu",
    slug: "samburu",
    description: "El Special Five – jirafa reticulada, cebra de Grévy, avestruz somalí, órice y gacela de Beisa",
    image: "/samburu.jpg",
    longDescription: "Samburu en el norte de Kenia ofrece una experiencia safari única con su Special Five: la jirafa reticulada, la cebra de Grévy, la avestruz somalí, el órice beisa y la gacela de Beisa. Los paisajes desérticos impresionantes y la cultura samburu auténtica complementan la experiencia. Los safaris son más exclusivos aquí, con menos turistas que los parques del sur.",
    attractions: ["Special Five", "Cultura samburu", "Paisajes desérticos", "Safari exclusivo", "Avistamiento de aves", "Río Ewaso Ng'iro"],
    bestTime: "Octubre a marzo",
    updatedAt: new Date(),
  },
  {
    id: "nakuru",
    name: "Lago Nakuru",
    slug: "nakuru",
    description: "Millones de flamencos y santuario de rinocerontes – parque pequeño pero rico",
    image: "/lake-nakuru.jpg",
    longDescription: "El Parque Nacional del Lago Nakuru es celebrado por sus millones de flamencos que crean un espectáculo rosa espectacular en el lago alcalino. El parque también es un santuario importante para los rinocerontes negros y blancos, con una de las mejores poblaciones de Kenia. Los paisajes varían desde las orilla del lago hasta bosques de acacia y riscos.",
    attractions: ["Flamencos", "Santuario de rinocerontes", "Avistamiento de aves", "Bosques", "Babuinos y monos", "Vista del Rift"],
    bestTime: "Octubre a marzo (temporada seca)",
    updatedAt: new Date(),
  },
  {
    id: "naivasha",
    name: "Lago Naivasha",
    slug: "naivasha",
    description: "Botes, hipopótamos y Crescent Island – escape relajante cerca de Nairobi",
    image: "/naivasha.jpg",
    longDescription: "El Lago Naivasha es uno de los lagos de agua dulce más hermosos de Kenia, ubicado a solo 90 minutos de Nairobi en el Valle del Rift. Famoso por safaris en bote donde puede acercarse a los hipopótamos, águilas pescadoras y cientos de especies de aves. Disfrute del ciclismo y game drives en el Parque Nacional de Hell's Gate – el único parque de Kenia donde puede caminar o andar en bicicleta entre cebras, jirafas y búfalos.",
    attractions: ["Safari en bote en el lago", "Avistamiento de hipopótamos", "Hell's Gate – Ciclismo y senderismo", "Crescent Island – Safari a pie", "Crater Lake para flamencos", "Aguas termales"],
    bestTime: "Todo el año",
    updatedAt: new Date(),
  },
  {
    id: "meru",
    name: "Meru",
    slug: "meru",
    description: "Naturaleza intacta – experiencia safari auténtica fuera de los caminos trillados",
    image: "/meru.jpg",
    longDescription: "Meru es una de las regiones safari más preservadas de Kenia, ofreciendo una experiencia auténtica lejos del turismo masivo. El Parque Nacional de Meru albergaba los últimos rinocerontes negros de Kenia en los años 80, y su población ha sido restaurada. Los safaris fuera de camino están permitidos, permitiendo encuentros excepcionales con vida silvestre en esta naturaleza preservada.",
    attractions: ["Naturaleza preservada", "Rinocerontes negros", "Safari fuera de camino", "Sistemas fluviales", "Fotografía de fauna", "Experiencia auténtica"],
    bestTime: "Octubre a marzo",
    updatedAt: new Date(),
  },
];

// Complete hotel translations for Spanish - ALL HOTELS
export const hotelsES = [
  // ========== NAIROBI HOTELS ==========
  {
    id: "nairobi-001",
    name: "Safari Park Hotel",
    location: "Nairobi",
    price: 350,
    rating: 4.8,
    image: "/safariparkhotel.jpg",
    description: "Hotel de lujo con temática safari con vista directa al Parque Nacional de Nairobi. Comodidades de clase mundial y experiencias gastronómicas excepcionales. Este hotel emblemático combina la elegancia colonial con la comodidad moderna.",
    amenities: ["WiFi", "Piscina", "Spa", "Restaurant", "Bar", "Salas de Conferencia", "Parking", "Servicio de Habitación"],
  },
  {
    id: "nairobi-002",
    name: "Crowne Plaza Nairobi Airport",
    location: "Aeropuerto de Nairobi",
    price: 280,
    rating: 4.6,
    image: "/CrownePlazaNairobi.jpg",
    description: "Hotel premium 5 estrellas convenientemente ubicado en el Aeropuerto Internacional Jomo Kenyatta. Decoración africana contemporánea y servicio excepcional. Cuenta con habitaciones accesibles con duchasy barras de apoyo.",
    amenities: ["WiFi", "Piscina", "Centro de Fitness", "Multiple Restaurantes", "Bar", "Spa", "Concierge", "Parking", "Shuttle del Aeropuerto", "Recepción 24h", "Centro de Negocios", "Instalaciones Accesibles"],
  },
  {
    id: "nairobi-003",
    name: "Serena Hotel Nairobi",
    location: "Nairobi",
    price: 320,
    rating: 4.7,
    image: "/SerenaHotelNairobi.jpg",
    description: "Hotel elegante que combina arquitectura contemporánea con elementos artísticos africanos. Servicio-premido y gastronomía excepcional con vistas a la ciudad.",
    amenities: ["WiFi", "Piscina", "Spa", "Gastronomía", "Centro de Negocios", "Centro de Fitness", "Parking", "Concierge"],
  },
  {
    id: "nairobi-004",
    name: "Villa Rosa Kempinski",
    location: "Nairobi",
    price: 400,
    rating: 4.9,
    image: "/VillaRosaKempinski.avif",
    description: "Hotel ultra lujoso 5 estrellas con servicio impecable. Restaurantes gastronómicos e instalaciones de spa de clase mundial. La experiencia de lujo definitivo en Nairobi.",
    amenities: ["WiFi", "Piscina de Lujo", "Spa", "5 Restaurantes", "Bar", "Gimnasio", "Servicio de Valet", "Concierge 24/7"],
  },
  {
    id: "nairobi-005",
    name: "The Bomas of Kenya Resort",
    location: "Nairobi",
    price: 250,
    rating: 4.5,
    image: "/bhero.webp",
    description: "Resort único que ofrece experiencias culturales keniatanas auténticas con alojamiento tradicional y moderno. Espectáculos culturales diarios y cocina tradicional.",
    amenities: ["WiFi", "Restaurant", "Espectáculos Culturales", "Jardín", "Salas de Reuniones", "Parking", "Bar", "Visitas Guiadas"],
  },
  {
    id: "nairobi-006",
    name: "Hilton Nairobi",
    location: "Nairobi",
    price: 230,
    rating: 4.4,
    image: "/HiltonNairobi.jpg",
    description: "Hotel moderno 4 estrellas con ubicación conveniente en el centro. Perfecto para viajeros de negocios y placer. Servicios completos y comodidad moderna.",
    amenities: ["WiFi", "Centro de Fitness", "Restaurant", "Bar", "Centro de Negocios", "Parking", "Salón", "Servicio de Habitación"],
  },
  {
    id: "nairobi-007",
    name: "Ibis Styles Nairobi",
    location: "Nairobi",
    price: 180,
    rating: 4.3,
    image: "/IbisStylesNairobi.jpg",
    description: "Hotel contemporáneo 3 estrellas con excelente relación calidad-precio con habitaciones cómodas y servicio de calidad. Diseño moderno y colores vivos.",
    amenities: ["WiFi", "Restaurant", "Bar", "Salas de Reuniones", "Parking", "TV", "Aire Acondicionado", "Ascensor"],
  },
  {
    id: "nairobi-008",
    name: "Radisson Blu Nairobi",
    location: "Nairobi",
    price: 290,
    rating: 4.6,
    image: "/RadissonBluNairobi.jpg",
    description: "Hotel premium 5 estrellas con comodidades modernas y servicio atento. Ubicado en el distrito de negocios prime de Westlands. Vistas a la ciudad e instalaciones de relajación.",
    amenities: ["WiFi", "Piscina", "Spa", "Multiple Restaurantes", "Gimnasio", "Centro de Negocios", "Parking", "Concierge"],
  },
  {
    id: "nairobi-009",
    name: "Four Points by Sheraton",
    location: "Nairobi",
    price: 260,
    rating: 4.5,
    image: "/FourPointsbySheraton.jpg",
    description: "Hotel contemporáneo 4 estrellas con excelentes opciones gastronómicas e instalaciones de negocios. Ubicación ideal para negocios y turismo.",
    amenities: ["WiFi", "Piscina", "Restaurant", "Bar", "Centro de Fitness", "Centro de Negocios", "Parking", "Servicio de Habitación"],
  },
  {
    id: "nairobi-010",
    name: "Mercure Hotel Nairobi",
    location: "Nairobi",
    price: 200,
    rating: 4.4,
    image: "/MercureHotelNairobi.jpg",
    description: "Hotel 4 estrellas con excelente ubicación y habitaciones cómodas. Excelente relación calidad-precio en el centro de Nairobi. Servicio profesional e instalaciones modernas.",
    amenities: ["WiFi", "Restaurant", "Bar", "Jardín", "Salas de Reuniones", "Parking", "TV", "Servicio de Habitación"],
  },
  {
    id: "nairobi-011",
    name: "Country Club Hotel",
    location: "Nairobi",
    price: 190,
    rating: 4.2,
    image: "/CountryClubHotel.jpeg",
    description: "Hotel económico 3 estrellas con hospitalidad cálida y ubicación conveniente. Atmósfera familiar y servicios esenciales de calidad.",
    amenities: ["WiFi", "Restaurant", "Bar", "Parking", "Jardín", "Servicio de Habitación", "TV", "Aire Acondicionado"],
  },
  {
    id: "nairobi-012",
    name: "Giraffe Manor",
    location: "Nairobi",
    price: 750,
    rating: 4.9,
    image: "/giraffe-manor.webp",
    description: "Desayuno con jirafas. Uno de los hoteles más icónicos de África. Boutique hotel único donde las jirafas de Rothschild en peligro visitan diariamente para alimentarse. Experiencia inolvidable.",
    amenities: ["Alimentación de Jirafas", "Jardines", "Gastronomía", "Propiedad Patrimonial", "Biblioteca", "WiFi Gratis", "Restaurant", "Bar"],
  },
  {
    id: "nairobi-014",
    name: "Tamarind Tree Hotel",
    location: "Nairobi",
    price: 220,
    rating: 4.4,
    image: "/2025-10-15.jpg",
    description: "Hotel moderno que ofrece hospedaje cómodo con una mezcla de estilo contemporáneo y charme africano. Restaurante en la azotea con vista a la ciudad y habitaciones accesibles con duchasy barras.",
    amenities: ["WiFi", "Restaurante en Azotea", "Bar", "Piscina", "Centro de Fitness", "Spa", "Centro de Negocios", "Parking", "Servicio de Habitación", "Instalaciones Accesibles"],
  },
  {
    id: "nairobi-015",
    name: "Sarova Panafric Hotel",
    location: "Nairobi",
    price: 220,
    rating: 4.5,
    image: "/2026-01-28.jpg",
    description: "Hotel emblemático de Nairobi con jardines tropicales y una rica historia que se remonta a 1965. Habitaciones accesibles con duchasy a pocos minutos del centro de la ciudad.",
    amenities: ["WiFi", "Piscina", "Restaurant", "Bar", "Jardín", "Instalaciones de Conferencia", "Parking", "Servicio de Habitación", "Instalaciones Accesibles"],
  },
  // ========== MAASAI MARA HOTELS ==========
  {
    id: "maasai-mara-001",
    name: "Mara Serena Safari Lodge",
    location: "Maasai Mara",
    price: 450,
    rating: 4.7,
    image: "/mara-1.jpg",
    description: "Lodge icónico encaramado en una colina con vista panorámica a la Gran Migración. Safaris incluidos, cocina gourmet y experiencia safari auténtica.",
    amenities: ["WiFi", "Piscina", "Spa", "Restaurant", "Bar", "Safari", "Vista a la Migración"],
  },
  {
    id: "maasai-mara-002",
    name: "Mara Intrepids Camp",
    location: "Maasai Mara",
    price: 380,
    rating: 4.5,
    image: "/mara-2.jpg",
    description: "Campamento de lujo con tiendas espaciosas y terraza privada. Safari en vehículo 4x4 con guías experimentados. Posición ideal a lo largo del río Talek.",
    amenities: ["WiFi", "Restaurant", "Bar", "Safari 4x4", "Tiendas de Lujo", "Terraza Privada"],
  },
  {
    id: "maasai-mara-009",
    name: "Angama Mara",
    location: "Maasai Mara",
    price: 1250,
    rating: 4.9,
    image: "/angama-mara.jpg",
    description: "En lo alto del Escarpamiento de Oloololo con vista panorámica del Triángulo de la Mara. Este lodge galardonado cuenta con 30 suites tentadas con paredes de vidrio del piso al techo, terrazas privadas y servicio excepcional. Experiencia de safari definitiva.",
    amenities: ["Piscina Infinity", "Spa", "Centro de Fitness", "Estudio de Fotografía", "Boutique", "Restaurant", "Bar", "Safaris en Globo", "Experiencias Culturales Masai", "Servicio de Mayordomo", "WiFi"],
  },
  {
    id: "maasai-mara-010",
    name: "Ashnil Mara Camp",
    location: "Maasai Mara",
    price: 420,
    rating: 4.6,
    image: "/unnamed (18).webp",
    description: "Campamento de lujo ubicado a lo largo del río Talek en la reserva privada de Maasai Mara. Excelente para avistamiento de fauna, acceso al río y avistamientos frecuentes de vida silvestre directamente desde el campamento.",
    amenities: ["WiFi", "Safaris", "Todas las Comidas", "Vista al Río", "Bar", "Caminatas en la Selva", "Fotografía", "Guías"],
  },
  {
    id: "maasai-mara-011",
    name: "Soroi Mara Bush Camp",
    location: "Maasai Mara",
    price: 480,
    rating: 4.7,
    image: "/mbc_main-30 (1).webp",
    description: "Campamento ecológico íntimo en un área de concesión privada de Maasai Mara que ofrece experiencias auténticas, guía excepcional y diseño de bajo impacto.",
    amenities: ["Todo Incluido", "Safaris", "Caminatas", "Comidas en la Selva", "Bar", "Ecológico", "Guías"],
  },
  {
    id: "maasai-mara-012",
    name: "Soroi Larsens Camp",
    location: "Maasai Mara",
    price: 520,
    rating: 4.8,
    image: "/2024-07-12.webp",
    description: "Campamento de lujo clásico con elegancia atemporal, servicio excelente y ubicación ideal presenciar los cruces del río durante la Gran Migración.",
    amenities: ["Todo Incluido", "Safaris", "Globo", "Gastronomía", "Spa", "Bar", "Guías"],
  },
  {
    id: "maasai-mara-013",
    name: "Soroi Private Wing",
    location: "Maasai Mara",
    price: 680,
    rating: 4.9,
    image: "/unnamed (35).webp",
    description: "Ala privada exclusiva dentro del Mara Serena Safari Lodge que ofrece privacidad máxima, servicio personalizado y vistas panorámicas de las llanuras de la Mara.",
    amenities: ["Mayordomo Privado", "Todo Incluido", "Safaris", "Comida Privada", "Tratamientos Spa", "Piscina Infinity", "WiFi"],
  },
  {
    id: "maasai-mara-014",
    name: "Mara Maisha",
    location: "Maasai Mara",
    price: 450,
    rating: 4.6,
    image: "/2025-12-10.webp",
    description: "Eco-lodge contemporáneo con tiendas elegantes, piscina infinity con vista a la Mara y excelente avistamiento de fauna en un escenario de concesión privada.",
    amenities: ["WiFi", "Piscina Infinity", "Safaris", "Caminatas", "Restaurant", "Bar", "Spa"],
  },
  {
    id: "maasai-mara-015",
    name: "Keekorok Lodge",
    location: "Maasai Mara",
    price: 340,
    rating: 4.4,
    image: "/BOB04192_HDR.webp",
    description: "Lodge clásico de servicio completo ubicado dentro de la Reserva Nacional de Maasai Mara con vista directa al punto de agua, piscina y safaris confiables.",
    amenities: ["WiFi", "Piscina", "Safaris", "Restaurant", "Bar", "Desayuno en la Selva", "Guías"],
  },
  // ========== AMBOSELI HOTELS ==========
  {
    id: "amboseli-001",
    name: "Ol Tukai Lodge Amboseli",
    location: "Amboseli",
    price: 420,
    rating: 4.8,
    image: "/pool-area.jpg",
    description: "Lodge de lujo con vistas impresionantes del monte Kilimanjaro y experiencias excepcionales de vida silvestre. Ubicación privilegiada en el corazón del Parque Nacional de Amboseli.",
    amenities: ["Safaris", "Restaurant", "Bar", "Piscina", "Fotografía", "WiFi", "Spa", "Guías"],
  },
  {
    id: "amboseli-007",
    name: "Ol Donyo Lodge",
    location: "Amboseli",
    price: 980,
    rating: 4.9,
    image: "/ol-donyo-lodge.jpg",
    description: "Lodge espectacular en las Chyulu Hills con vistas breathtaking del monte Kilimanjaro. Experiencia safari exclusiva con piscinas privadas, safaris a caballo y camas de estrellas para dormir bajo el cielo africano. Suites accesibles con duchasy amplias puertas.",
    amenities: ["Piscinas Privadas", "Safaris a Caballo", "Camas de Estrellas", "Gimnasio", "Spa", "WiFi Gratis", "Restaurant", "Bar", "Vistas Kilimanjaro", "Safaris", "Caminatas", "Instalaciones Accesibles"],
  },
  {
    id: "amboseli-008",
    name: "Praro Amboseli Camp",
    location: "Amboseli",
    price: 250,
    rating: 4.5,
    image: "/poraro-amboseli-tent-1.jpg",
    description: "Una rama orgullosa de los Zebra Plains Mara Camps, Praro Amboseli Camp ofrece una experiencia safari auténtica con alojamiento accesible y el majestic telón de fondo del monte Kilimanjaro. Amplias tiendas, duchasy barras de apoyo.",
    amenities: ["Vistas Kilimanjaro", "Restaurant", "Bar", "Safaris", "Caminatas", "Fogata", "Tienda de Regalos", "Parking", "Energía Solar", "WiFi (Áreas Comunes)", "Instalaciones Accesibles", "Vehículos Safari Accesibles"],
  },
  {
    id: "amboseli-010",
    name: "Kibo Safari Camp",
    location: "Amboseli",
    price: 260,
    rating: 4.5,
    image: "/unnamed(7).jpg",
    description: "Parte de la prestigiosa Kibo Collection, este hotel boutique ofrece servicio personalizado, alojamiento elegante y un tranquilo jardín. Totalmente accesible con duchasy puertas amplias.",
    amenities: ["WiFi", "Restaurant", "Bar", "Jardín", "Traslados al Aeropuerto", "Servicio de Habitación", "Instalaciones de Conferencia", "Parking", "Spa", "Instalaciones Accesibles"],
  },
  // ========== NAKURU HOTELS ==========
  {
    id: "nakuru-003",
    name: "Lake Nakuru Lodge",
    location: "Lago Nakuru",
    price: 280,
    rating: 4.5,
    image: "/lake-nakuru.jpg",
    description: "Lodge con vista al Parque Nacional del Lago Nakuru. Punto de vista ideal para observar flamencos y rinocerontes. Ubicación privilegiada cerca del lago alcalino.",
    amenities: ["WiFi", "Restaurant", "Bar", "Safari", "Avistamiento de Aves", "Vista al Lago"],
  },
  {
    id: "nakuru-004",
    name: "Sarova Whitesands Beach Resort",
    location: "Lago Nakuru",
    price: 320,
    rating: 4.6,
    image: "/whitesands.jpg",
    description: "Complejo hotelero de lujo en las orillas del Lago Nakuru con playas privadas e instalaciones de ocio completas. Perfecto para familias y parejas.",
    amenities: ["Piscina", "Spa", "Restaurant", "Bar", "Playa", "Actividades Acuáticas", "Niños"],
  },
  // ========== NAIVASHA HOTELS ==========
  {
    id: "naivasha-001",
    name: "Lake Naivasha Crescent Camp",
    location: "Naivasha",
    price: 320,
    rating: 4.7,
    image: "/cresentlake.avif",
    description: "Campamento de lujo en las orillas del Lago Naivasha con impresionantes vistas al lago y excelente avistamiento de vida silvestre. Atmósfera pacífica en medio de la naturaleza.",
    amenities: ["WiFi", "Restaurant", "Bar", "Actividades en el Lago", "Safaris", "Spa", "Salón", "Servicio de Habitación"],
  },
  {
    id: "naivasha-002",
    name: "Naivasha Serena Camp",
    location: "Naivasha",
    price: 300,
    rating: 4.6,
    image: "/serenacamp.jpg",
    description: "Campamento todo incluido con experiencia safari auténtica y hospitalidad excepcional. Comidas incluidas y safaris diarios en la reserva del Lago Naivasha.",
    amenities: ["Comidas Incluidas", "Safaris", "Actividades del Lago", "Chimenea", "Bar", "Spa", "Fotografía", "WiFi"],
  },
  {
    id: "naivasha-003",
    name: "Hells Gate Game Lodge",
    location: "Naivasha",
    price: 280,
    rating: 4.5,
    image: "/hellsgate.jpeg",
    description: "Lodge de safari cerca del Parque Nacional de Hell's Gate con excelentes oportunidades de safari y atmósfera acogedora. Fácil acceso a actividades de ciclismo y senderismo.",
    amenities: ["Restaurant", "Bar", "Safaris", "Senderismo", "Escalada", "Parking", "WiFi", "Servicio de Habitación"],
  },
  {
    id: "naivasha-004",
    name: "Lake Naivasha Sopa Resort",
    location: "Naivasha",
    price: 280,
    rating: 4.5,
    image: "/2025-12-22.webp",
    description: "Resort familiar en las orillas del Lago Naivasha con hermosos jardines, piscina y fácil acceso a paseos en barco, avistamiento de aves y Parque Nacional de Hell's Gate.",
    amenities: ["WiFi", "Piscina", "Restaurant", "Bar", "Paseos en Barco", "Instalaciones de Conferencia", "Jardines"],
  },
  {
    id: "naivasha-005",
    name: "Lake Naivasha Simba Lodge",
    location: "Naivasha",
    price: 220,
    rating: 4.3,
    image: "/unnamed (61).webp",
    description: "Lodge cómodo de categoría media con proximidad al lago, buenas instalaciones y base conveniente para Hell's Gate, Crescent Island y safaris en barco.",
    amenities: ["WiFi", "Restaurant", "Bar", "Piscina", "Actividades del Lago", "Parking"],
  },
  {
    id: "naivasha-008",
    name: "Muthu Lake Naivasha Country Club",
    location: "Naivasha",
    price: 280,
    rating: 4.5,
    image: "/muthu-lake-naivasha.jpg",
    description: "Elegante country club en las orillas del Lago Naivasha que ofrece una combinación perfecta de encanto colonial y comodidad moderna. Rodeado de jardines exuberantes con impresionantes vistas al lago. Totalmente accesible.",
    amenities: ["WiFi", "Piscina", "Restaurant", "Bar y Salón", "Canchas de Tenis", "Paseos en Barco", "Avistamiento de Aves", "Vistas al Jardín", "Instalaciones de Conferencia", "Parking", "Servicio de Habitación", "Seguridad 24h", "Instalaciones Accesibles"],
  },
  // ========== SAMBURU HOTELS ==========
  {
    id: "samburu-001",
    name: "Samburu Intrepids Tented Camp",
    location: "Samburu",
    price: 400,
    rating: 4.8,
    image: "/samburu-intrepids-luxury (5).jpg",
    description: "Lodge ultra de lujo en el río Ewaso Nyiro con experiencias safari excepcionales y servicio personalizado. Ubicación ideal para observar el Special Five.",
    amenities: ["Todo Incluido", "Safaris", "Actividades del Río", "Spa", "Bar", "Gastronomía", "Fotografía", "Guías"],
  },
  {
    id: "samburu-005",
    name: "Ashnil Samburu Camp",
    location: "Samburu",
    price: 280,
    rating: 4.3,
    image: "/ashnil-samburu-camp.jpg",
    description: "Lodge bien posicionado con excelente avistamiento de fauna cerca de Buffalo Springs. Instalaciones completas y atmósfera pacífica en la reserva de Samburu.",
    amenities: ["Safaris", "Restaurant", "Bar", "Parking", "Servicio de Habitación", "WiFi", "Fotografía", "Guías"],
  },
  // ========== NANYUKI HOTELS ==========
  {
    id: "nanyuki-012",
    name: "Sweetwaters Tented Camp",
    location: "Nanyuki",
    price: 380,
    rating: 4.7,
    image: "/sweetwaters-tented-camp-main.jpg",
    description: "Campamento de lujo ubicado dentro de la Reserva Privada de Ol Pejeta, que ofrece avistamiento excepcional de vida silvestre con un charco de agua privado y vistas impresionantes del Monte Kenia. Experiencia mágica en el corazón de la naturaleza.",
    amenities: ["WiFi", "Restaurant", "Bar", "Piscina", "Parking", "Servicio de Habitación", "Seguridad 24h", "Terraza de Observación", "Tienda de Regalos", "Servicio de Lavandería", "Spa", "Safaris", "Safaris Nocturnos", "Visitas al Santuario de Chimpancés"],
  },
  // ========== TSAVO WEST HOTELS ==========
  {
    id: "tsavo-west-007",
    name: "Finch Hattons",
    location: "Tsavo Oeste",
    price: 850,
    rating: 4.8,
    image: "/finch-hattons.jpg",
    description: "Oasis de lujo en el corazón del Parque Nacional de Tsavo Oeste, ubicado alrededor de un manantial natural que atrae abundante vida silvestre. Suites tentadas exquisitas, spa de clase mundial y experiencias gastronómicas excepcionales. Totalmente accesible con duchasy barras de apoyo.",
    amenities: ["Piscinas Privadas de Manantial", "Spa", "Cancha de Tenis", "Bodega", "Servicio de Mayordomo", "Gimnasio", "WiFi Gratis", "Restaurant", "Bar", "Safaris", "Avistamiento de Aves", "Caminatas", "Instalaciones Accesibles"],
  },
  // ========== NAIVASHA ADDITIONAL HOTELS ==========
  {
    id: "naivasha-006",
    name: "Lake Naivasha Resort",
    location: "Naivasha",
    price: 260,
    rating: 4.4,
    image: "/unnamed (71).webp",
    description: "Propiedad moderna tipo complejo en el Lago Naivasha con múltiples opciones de restaurantes, piscina y fácil acceso a paseos en barco y avistamiento de aves.",
    amenities: ["WiFi", "Piscina", "Multiple Restaurantes", "Bar", "Safaris en Boto", "Salas de Conferencia"],
  },
  {
    id: "naivasha-007",
    name: "Enashipai Resort & Spa",
    location: "Naivasha",
    price: 320,
    rating: 4.6,
    image: "/2025-05-21.webp",
    description: "Resort de lujo en las orilla del Lago Naivasha que ofrece habitaciones elegantes, spa completo, múltiples opciones de restaurantes y excelentes instalaciones para relajación, conferencias y actividades lacustres. Habitaciones accesibles con duchasy barras de apoyo.",
    amenities: ["WiFi", "Piscinas Múltiples", "Spa Completo", "Multiple Restaurantes", "Bar y Salón", "Actividades del Lago y Paseos en Bote", "Instalaciones de Conferencia y Eventos", "Centro de Fitness", "Jardines", "Instalaciones Accesibles"],
  },
  // ========== NAKURU ADDITIONAL HOTELS ==========
  {
    id: "nakuru-005",
    name: "Hotel Panorama Resort",
    location: "Lago Nakuru",
    price: 210,
    rating: 4.3,
    image: "/hotel-panorama-resort.jpg",
    description: "Hotel con vistas panorámicas y habitaciones cómodas con vistas a la ciudad de Nakuru. Vista a las montañas circundantes.",
    amenities: ["WiFi", "Restaurant", "Bar", "Vistas", "Parking", "Servicio de Habitación", "Jardín", "TV"],
  },
  {
    id: "nakuru-006",
    name: "The Lake Nakuru Flamingo Lodge",
    location: "Lago Nakuru",
    price: 240,
    rating: 4.4,
    image: "/welcome-to-lake-nakuru.jpg",
    description: "Lodge temático sobre la naturaleza que celebra los famosos flamencos de Nakuru con hospedaje cómodo.",
    amenities: ["WiFi", "Restaurant", "Piscina", "Bar", "Jardín", "Parking", "Servicio de Habitación", "TV"],
  },
  {
    id: "nakuru-007",
    name: "Lake Nakuru Lodge",
    location: "Lago Nakuru",
    price: 220,
    rating: 4.3,
    image: "/lake-nakuru-lodge (1).jpg",
    description: "Lodge dentro de los límites del Parque Nacional del Lago Nakuru con acceso directo a la vida silvestre. Avistamiento de flamencos desde el lodge.",
    amenities: ["WiFi", "Restaurant", "Bar", "Safaris", "Parking", "Servicio de Habitación", "Jardín", "Guías"],
  },
  {
    id: "nakuru-008",
    name: "Rock Hyrax Hotel",
    location: "Lago Nakuru",
    price: 170,
    rating: 4.1,
    image: "/caption.jpg",
    description: "Hotel acogedor con atmósfera cálida y tarifas accesibles. Centro de Nakuru.",
    amenities: ["WiFi", "Restaurant", "Bar", "Parking", "Servicio de Habitación", "TV", "Aire Acondicionado", "Jardín"],
  },
  {
    id: "nakuru-009",
    name: "Ziwa Bush Lodge",
    location: "Lago Nakuru",
    price: 150,
    rating: 4.0,
    image: "/private-lovely-large.jpg",
    description: "Hotel económico que ofrece habitaciones limpias y servicios básicos pero de calidad. Buena relación calidad-precio.",
    amenities: ["WiFi", "Restaurant", "Bar", "Parking", "Servicio de Habitación", "TV", "Aire Acondicionado"],
  },
  {
    id: "nakuru-010",
    name: "Lake Nakuru Sopa Lodge",
    location: "Lago Nakuru",
    price: 190,
    rating: 4.2,
    image: "/lake-nakuru-sopa-lodge (1).jpg",
    description: "Hotel de 3 estrellas con excelentes instalaciones y ubicación conveniente. Vista a las colinas circundantes.",
    amenities: ["WiFi", "Restaurant", "Piscina", "Bar", "Jardín", "Parking", "Servicio de Habitación", "TV"],
  },
  {
    id: "nakuru-011",
    name: "Punda Milias Nakuru Camp",
    location: "Lago Nakuru",
    price: 215,
    rating: 4.3,
    image: "/aerial-view-of-pundamilias.jpg",
    description: "Hotel moderno de 3 estrellas con diseño temático safari e instalaciones de calidad. Cerca del parque nacional.",
    amenities: ["WiFi", "Restaurant", "Piscina", "Bar", "Jardín", "Parking", "Servicio de Habitación", "Gimnasio"],
  },
  {
    id: "nakuru-012",
    name: "Sarova Lion Hill Game Lodge",
    location: "Lago Nakuru",
    price: 320,
    rating: 4.7,
    image: "/unnamed (1).webp",
    description: "Ubicado dentro del Parque Nacional del Lago Nakuru, este impresionante lodge ofrece vistas breathtaking del lago y los flamencos. Habitaciones accesibles con duchasy barras de apoyo.",
    amenities: ["WiFi", "Piscina", "Restaurant", "Bar", "Safaris", "Spa", "Tienda de Regalos", "Parking", "Instalaciones Accesibles"],
  },
  {
    id: "nakuru-013",
    name: "Sarova Woodlands Hotel & Spa",
    location: "Lago Nakuru",
    price: 280,
    rating: 4.6,
    image: "/Sarova-Woodlands-Nakuru.webp",
    description: "Una retraite tranquila en el corazón de Nakuru, que ofrece hospedaje lujoso y spa completo. Totalmente accesible con duchasy áreas públicas accesibles.",
    amenities: ["WiFi", "Piscina", "Spa", "Restaurant", "Bar", "Instalaciones de Conferencia", "Parking", "Servicio de Habitación", "Instalaciones Accesibles"],
  },
  {
    id: "nakuru-014",
    name: "Lake Nakuru Sopa Lodge",
    location: "Lago Nakuru",
    price: 290,
    rating: 4.4,
    image: "/lake-nakuru-sopa-lodge (5).jpg",
    description: "Lodge bien ubicado cerca del Parque Nacional del Lago Nakuru con vistas a los flamencos, habitaciones cómodas y buenas instalaciones para avistamiento de aves y safaris.",
    amenities: ["WiFi", "Piscina", "Restaurant", "Bar", "Safaris", "Avistamiento de Aves"],
  },
  {
    id: "nakuru-015",
    name: "Lake Nakuru Lodge",
    location: "Lago Nakuru",
    price: 240,
    rating: 4.3,
    image: "/Lake Nakuru Lodge (35).webp",
    description: "Lodge cómodo con vista al Lago Nakuru y fácil acceso a las actividades safari. Base ideal para explorar el parque nacional.",
    amenities: ["WiFi", "Restaurant", "Bar", "Safaris", "Parking", "Servicio de Habitación"],
  },
  // ========== KISUMU HOTEL ==========
  {
    id: "kisumu-001",
    name: "Sarova Imperial Hotel",
    location: "Kisumu",
    price: 210,
    rating: 4.5,
    image: "/2023-01-24.webp",
    description: "Con vistas al Lago Victoria, este elegante hotel ofrece vistas impresionantes al lago y modernas instalaciones. Habitaciones accesibles con duchasy fácil acceso a las atracciones de Kisumu.",
    amenities: ["WiFi", "Restaurant", "Bar", "Vistas al Lago", "Instalaciones de Conferencia", "Parking", "Servicio de Habitación", "Instalaciones Accesibles"],
  },
  // ========== MOMBASA HOTEL ==========
  {
    id: "mombasa-001",
    name: "Sarova Whitesands Beach Resort & Spa",
    location: "Mombasa",
    price: 350,
    rating: 4.8,
    image: "/2026-03-09.webp",
    description: "El principal complejo playero de Mombasa, ubicado en kilómetros de arena blanca pristine a lo largo del Océano Índico. Totalmente accesible con duchasy barras de apoyo, pasillos accesibles y sillas de ruedas de playa disponibles.",
    amenities: ["WiFi", "Piscinas Múltiples", "Spa", "Multiple Restaurantes", "Bars", "Deportes Acuáticos", "Club de Niños", "Parking", "Instalaciones Accesibles", "Sillas de Ruedas de Playa"],
  },
];

export const faqsES = [
  { question: "¿Cuál es la mejor época para un safari en Kenia?", answer: "La mejor época es de junio a octubre para la temporada seca y la Gran Migración. Diciembre a marzo también es excelente con menos lluvia. Sin embargo, cada destino tiene sus propias temporadas óptimas." },
  { question: "¿Necesito visa para Kenia?", answer: "La mayoría de los visitantes necesitan una visa para entrar a Kenia. Puede obtener una visa electrónica a través del portal de inmigración de Kenia en línea, o obtener una visa a la llegada. Los requisitos varían según la nacionalidad." },
  { question: "¿Es la malaria una preocupación en Kenia?", answer: "El riesgo de malaria varía según la ubicación y la temporada. La mayoría de los destinos safari en altitudes más altas tienen menor riesgo. Consulte con una clínica de salud de viaje antes de su viaje." },
  { question: "¿Qué vida silvestre puedo ver en Kenia?", answer: "Kenia ofrece los Big Five (león, leopardo, elefante, búfalo, rinoceronte), la Gran Migración, cientos de especies de aves y una diversidad increíble de vida silvestre." },
  { question: "¿Los safaris son adecuados para familias?", answer: "Sí, muchos lodges ofrecen actividades para niños, safaris adaptados para familias y servicios de niñería. Algunos lodges tienen programas especiales para niños." },
  { question: "¿Qué equipo debo llevar para mi safari?", answer: "Lleve ropa de colores neutros, capas para temperaturas variables, zapatos de caminar, sombrero, protector solar, binoculares y cámara. Se recomiendan mochilas suaves." },
  { question: "¿Cuál es la política de cancelación?", answer: "Las políticas de cancelación varían según el operador y la temporada. Generalmente, cancelación más de 30 días antes obtiene 25% de cargo, 15-30 días obtiene 50%, menos de 15 días obtiene 100%." },
  { question: "¿Es Kenia seguro para los turistas?", answer: "Kenia es generalmente seguro para los turistas en las zonas safari y turísticas establecidas. Recomendamos seguir los consejos de su operador y evitar zonas no recomendadas." },
];