// French translations for destinations, hotels and FAQs

export const locationsFR = [
  {
    id: "nairobi",
    name: "Nairobi",
    slug: "nairobi",
    description: "La capitale dynamique du Kenya – meilleurs hôtels de luxe, safaris au parc national de Nairobi, centre de girafes et expériences culturelles",
    image: "/Nairobi.avif",
    longDescription: "Nairobi, la capitale animée du Kenya et porte d'entrée principale des safaris d'Afrique de l'Est, combine l'énergie urbaine avec des expériences wildlife incroyables. Connue dans le monde entier comme la seule capitale avec un parc national en son sein, Nairobi offre des safaris au parc national de Nairobi à seulement 20 minutes du centre-ville. Visitez le célèbre Giraffe Centre, le musée Karen Blixen, le David's Sheldrick Elephant Orphanage, et le musée national de Nairobi. La ville abrite des hôtels de luxe, des lodges boutique, des restaurants sur les toits, une vie nocturne animée et d'excellents centres commerciaux.",
    attractions: ["Safari au parc national de Nairobi", "Giraffe Centre – Nourrir les girafes", "David Sheldrick Elephant & Rhino Orphanage", "Musée Karen Blixen (Out of Africa)", "Musée national de Nairobi", "Bomas of Kenya – Spectacle culturel", "Visites de Kibera Slum", "Nairobi Safari Walk", "Karura Forest – Randonnée"],
    bestTime: "Juin à octobre (saison sèche) et janvier à février",
    updatedAt: new Date(),
  },
  {
    id: "maasai-mara",
    name: "Maasai Mara",
    slug: "maasai-mara",
    description: "La Grande Migration, les Big Cats et les safaris en montgolfière – le parc national le plus célèbre du Kenya",
    image: "/maasai-mara.jpeg",
    longDescription: "Le Maasai Mara est la destination safari la plus emblématique du Kenya, mondialement connue pour la Grande Migration annuelle où plus de 1,5 million de gnous traversent les plaines de juillet à octobre. Le parc abrite une population dense de lions, léopards, guépards (les Big Cats), éléphants, girafes et zèbres. Les lodges de luxe offrent des vues sur les plaines infinies, et les safaris en montgolfière au lever du soleil sont une expérience inoubliable. La culture masaï authentique peut être vécue lors de visites de villages.",
    attractions: ["Grande Migration (juillet-octobre)", "Observation des lions et léopards", "Safari en montgolfière", "Visites de villages masaï", "Game drives au lever du soleil", "Migration des gnous et zèbres"],
    bestTime: "Juillet à octobre pour la migration, décembre à mars pour les naissances",
    updatedAt: new Date(),
  },
  {
    id: "amboseli",
    name: "Amboseli",
    slug: "amboseli",
    description: "Le royaume des éléphants avec le Kilimandjaro en arrière-plan – meilleur endroit pour voir des éléphants",
    image: "/amboseli.jpeg",
    longDescription: "Amboseli est mondialement connu pour ses vues imprenables sur le mont Kilimandjaro et ses grandes populations d'éléphants. Le parc offre certaines des meilleures opportunités de photographie wildlife au Kenya, avec des éléphants aux longues défenses marchant devant le glacier emblématique du Kilimandjaro. Les zones marécageuses (swamps) attirent des centaines d'oiseaux et d'autres animaux, et les couchers de soleil sur le parc sont spectaculaires.",
    attractions: ["Vue sur le Kilimandjaro", "Observation des éléphants", "Photographie wildlife", "Observation des oiseaux", "Safari dans les marais", "Couchers de soleil spectaculaires"],
    bestTime: "Octobre à mars (vue la plus claire sur le Kilimandjaro)",
    updatedAt: new Date(),
  },
  {
    id: "tsavo-east",
    name: "Tsavo Est",
    slug: "tsavo-east",
    description: "Le plus grand parc national du Kenya avec ses éléphants rouges emblématiques",
    image: "/tsavo-east.jpg",
    longDescription: "Tsavo Est est le plus grand parc national du Kenya, célébré pour ses élégants éléphants roux qui se baignent dans la poussière rouge caractéristique de la région. Le parc offre des safaris exclusifs loin des foules, avec des paysages variés allant des plaines arides aux collines rocheuses. Les lions sans crinière de Tsavo ajoutent au mystère de cette région sauvage.",
    attractions: ["Éléphants rouges de Tsavo", "Lions sans crinière", "Safari exclusif", "Paysages variés", "Observation des oiseaux", "Lac Mud"],
    bestTime: "Octobre à mars (saison sèche)",
    updatedAt: new Date(),
  },
  {
    id: "tsavo-west",
    name: "Tsavo Ouest",
    slug: "tsavo-west",
    description: "Volcans, sources chaudes et la célèbre Shetani Lava Flow",
    image: "/tsavo-west.jpg",
    longDescription: "Tsavo Ouest offre des paysages spectaculaires avec ses volcans, sources chaudes géothermiques et la célèbre coulée de lave Shetani. Le parc abrite une grande variété de faune incluant éléphants, lions, girafes et rhinocéros. Le lac Chala à la frontière tanzanienne offre des couchers de soleil magnifiques, et les grottes de Mzima offrent une vue sous l'eau sur les hippopotames.",
    attractions: ["Shetani Lava Flow", "Sources chaudes", "Volcans du parc", "Lac Chala", "Grottes de Mzima", "Rhinocéros"],
    bestTime: "Octobre à mars",
    updatedAt: new Date(),
  },
  {
    id: "samburu",
    name: "Samburu",
    slug: "samburu",
    description: "Le Special Five – girafe reticulée, zèbre de Grévy, autruche somali, oryx et gazelle de Beisa",
    image: "/samburu.jpg",
    longDescription: "Samburu dans le nord du Kenya offre une expérience safari unique avec son Special Five: la girafe reticulée, le zèbre de Grévy, l'autruche somali, l'oryx beisa et la gazelle de Beisa. Les paysages désertiques époustouflants et la culture samburu authentique complètent l'expérience. Les safaris sont plus exclusifs ici, avec moins de touristes que les parks du sud.",
    attractions: ["Special Five", "Culture samburu", "Paysages désertiques", "Safari exclusif", "Observation des oiseaux", "Rivière Ewaso Ng'iro"],
    bestTime: "Octobre à mars",
    updatedAt: new Date(),
  },
  {
    id: "nakuru",
    name: "Lac Nakuru",
    slug: "nakuru",
    description: "Des millions de flamants roses et sanctuaire de rhinocéros – parc national petit mais riche",
    image: "/lake-nakuru.jpg",
    longDescription: "Le parc national du lac Nakuru est célébré pour ses millions de flamants roses qui créent un spectacle rose spectaculaire sur le lac alcalin. Le parc est aussi un sanctuaire important pour les rhinocéros noirs et blancs, avec l'une des meilleures populations du Kenya. Les paysages varient des bords du lac aux forêts de séné et aux falaises.",
    attractions: ["Flamants roses", "Sanctuaire rhinocéros", "Observation des oiseaux", "Forêts", "Babouins et singes", "Vue sur le Rift"],
    bestTime: "Octobre à mars (saison sèche)",
    updatedAt: new Date(),
  },
  {
    id: "naivasha",
    name: "Lac Naivasha",
    slug: "naivasha",
    description: "Bateaux, hippopotames et Crescent Island – escapade détente près de Nairobi",
    image: "/naivasha.jpg",
    longDescription: "Le lac Naivasha est l'un des lacs d'eau douce les plus beaux du Kenya, situé à seulement 90 minutes de Nairobi dans la vallée du Rift. Fameux pour les safaris en bateau où vous pouvez vous approcher des hippopotames, des aigles pêcheurs et des centaines d'espèces d'oiseaux. Profitez du vélo et des game drives dans le parc national de Hell's Gate – le seul parc du Kenya où vous pouvez marcher ou faire du vélo parmi les zèbres, girafes et buffles.",
    attractions: ["Safari en bateau sur le lac", "Observation des hippopotames", "Hell's Gate – Vélo et randonnée", "Crescent Island – Safari à pied", "Lac Crater pour flamants", "Sources thermales"],
    bestTime: "Toute l'année",
    updatedAt: new Date(),
  },
  {
    id: "meru",
    name: "Meru",
    slug: "meru",
    description: "Wilderness intact – expérience safari authentique hors des sentiers battus",
    image: "/meru.jpg",
    longDescription: "Meru est l'une des régions safari les plus préservées du Kenya, offrant une expérience authentique loin du tourisme de masse. Le parc national de Meru abritait les derniers rhinocéros noirs du Kenya dans les années 80, et sa population a été restaurée. Les safari hors-piste sont autorisés, permettant des rencontres wildlife exceptionnelles dans cette nature préservée.",
    attractions: ["Wilderness préservée", "Rhinocéros noirs", "Safari hors-piste", "Rivières et systèmes fluviaux", "Chasse photographique", "Expérience authentique"],
    bestTime: "Octobre à mars",
    updatedAt: new Date(),
  },
];

// Complete hotel translations for French - ALL HOTELS
export const hotelsFR = [
  // ========== NAIROBI HOTELS ==========
  {
    id: "nairobi-001",
    name: "Safari Park Hotel",
    location: "Nairobi",
    price: 350,
    rating: 4.8,
    image: "/safariparkhotel.jpg",
    description: "Hôtel de luxe thématique safari avec vue directe sur le parc national de Nairobi. Équipements de classe mondiale et expériences gastronomiques exceptionnelles. Cet hôtel emblématique combine l'élégance coloniale avec le confort moderne, offrant une expérience safari unique au cœur de la capitale kényenne.",
    amenities: ["WiFi", "Piscine", "Spa", "Restaurant", "Bar", "Salles de Conférence", "Parking", "Service en chambre"],
  },
  {
    id: "nairobi-002",
    name: "Crowne Plaza Nairobi Airport",
    location: "Aéroport de Nairobi",
    price: 280,
    rating: 4.6,
    image: "/CrownePlazaNairobi.jpg",
    description: "Hôtel premium 5 étoiles idéalement situé à l'aéroport international Jomo Kenyatta. Décoration africaine contemporaine et service exceptionnel. Dispose de chambres accessibles avec douches à l'italienne et barres de maintien.",
    amenities: ["WiFi", "Piscine", "Salle de Sport", "Multiple Restaurants", "Bar", "Spa", "Concierge", "Parking", "Navette Aéroport", "Réception 24h", "Centre d'Affaires", "Installations Accessibles"],
  },
  {
    id: "nairobi-003",
    name: "Serena Hotel Nairobi",
    location: "Nairobi",
    price: 320,
    rating: 4.7,
    image: "/SerenaHotelNairobi.jpg",
    description: "Hôtel élégant alliant architecture contemporaine et éléments artistiques africains primés. Service et restauration exceptionnels avec vue sur la ville.",
    amenities: ["WiFi", "Piscine", "Spa", "Gastronomie", "Centre d'Affaires", "Salle de Sport", "Parking", "Concierge"],
  },
  {
    id: "nairobi-004",
    name: "Villa Rosa Kempinski",
    location: "Nairobi",
    price: 400,
    rating: 4.9,
    image: "/VillaRosaKempinski.avif",
    description: "Hôtel ultra-luxueux 5 étoiles avec service impeccable. Plusieurs restaurants gastronomiques et installations spa de classe mondiale. L'expérience de luxe ultime à Nairobi.",
    amenities: ["WiFi", "Piscine de Luxe", "Spa", "5 Restaurants", "Bar", "Gymnase", "Service de Voiturier", "Concierge 24/7"],
  },
  {
    id: "nairobi-005",
    name: "The Bomas of Kenya Resort",
    location: "Nairobi",
    price: 250,
    rating: 4.5,
    image: "/bhero.webp",
    description: "Complexe unique offrant des expériences culturelles kenyennes authentiques avec hébergements traditionnels et modernes. Spectacles culturels quotidiens et cuisine traditionnelle.",
    amenities: ["WiFi", "Restaurant", "Spectacles Culturels", "Jardin", "Salles de Réunion", "Parking", "Bar", "Visites Guidées"],
  },
  {
    id: "nairobi-006",
    name: "Hilton Nairobi",
    location: "Nairobi",
    price: 230,
    rating: 4.4,
    image: "/HiltonNairobi.jpg",
    description: "Hôtel moderne 4 étoiles avec emplacement pratique en centre-ville. Parfait pour les voyageurs d'affaires et de loisirs. Services complets et confort moderne.",
    amenities: ["WiFi", "Salle de Sport", "Restaurant", "Bar", "Centre d'Affaires", "Parking", "Salon", "Service en chambre"],
  },
  {
    id: "nairobi-007",
    name: "Ibis Styles Nairobi",
    location: "Nairobi",
    price: 180,
    rating: 4.3,
    image: "/IbisStylesNairobi.jpg",
    description: "Hôtel contemporain 3 étoiles offrant un excellent rapport qualité-prix avec chambres confortables et service de qualité. Design moderne et couleurs vives.",
    amenities: ["WiFi", "Restaurant", "Bar", "Salles de Réunion", "Parking", "TV", "Climatisation", "Ascenseur"],
  },
  {
    id: "nairobi-008",
    name: "Radisson Blu Nairobi",
    location: "Nairobi",
    price: 290,
    rating: 4.6,
    image: "/RadissonBluNairobi.jpg",
    description: "Hôtel premium 5 étoiles avec équipements modernes et service attentionné. Situé dans le quartier d'affaires prime de Westlands.Vue sur la ville et installations de détente.",
    amenities: ["WiFi", "Piscine", "Spa", "Multiple Restaurants", "Gymnase", "Centre d'Affaires", "Parking", "Concierge"],
  },
  {
    id: "nairobi-009",
    name: "Four Points by Sheraton",
    location: "Nairobi",
    price: 260,
    rating: 4.5,
    image: "/FourPointsbySheraton.jpg",
    description: "Hôtel contemporain 4 étoiles offrant d'excellentes options de restauration et installations commerciales. Emplacement idéal pour les affaires et le tourisme.",
    amenities: ["WiFi", "Piscine", "Restaurant", "Bar", "Salle de Sport", "Centre d'Affaires", "Parking", "Service en chambre"],
  },
  {
    id: "nairobi-010",
    name: "Mercure Hotel Nairobi",
    location: "Nairobi",
    price: 200,
    rating: 4.4,
    image: "/MercureHotelNairobi.jpg",
    description: "Hôtel 4 étoiles avec excellent emplacement et chambres confortables. Excellent rapport qualité-prix au centre de Nairobi. Service professionnel et installations modernes.",
    amenities: ["WiFi", "Restaurant", "Bar", "Jardin", "Salles de Réunion", "Parking", "TV", "Service en chambre"],
  },
  {
    id: "nairobi-011",
    name: "Country Club Hotel",
    location: "Nairobi",
    price: 190,
    rating: 4.2,
    image: "/CountryClubHotel.jpeg",
    description: "Hôtel économique 3 étoiles avec hospitalité chaleureuse et emplacement pratique. Atmosphère familiale et services essentiels de qualité.",
    amenities: ["WiFi", "Restaurant", "Bar", "Parking", "Jardin", "Service en chambre", "TV", "Climatisation"],
  },
  {
    id: "nairobi-012",
    name: "Giraffe Manor",
    location: "Nairobi",
    price: 750,
    rating: 4.9,
    image: "/giraffe-manor.webp",
    description: "Petit-déjeuner avec des girafes. L'un des hôtels les plus emblématiques d'Afrique. Boutique hotel unique où les girafes de Rothschild en danger visitent quotidiennement pour se nourrir. Expérience inoubliable.",
    amenities: ["Alimentation des Girafes", "Jardins", "Gastronomie", "Propriété Patrimoniale", "Bibliothèque", "WiFi Gratuit", "Restaurant", "Bar"],
  },
  {
    id: "nairobi-014",
    name: "Tamarind Tree Hotel",
    location: "Nairobi",
    price: 220,
    rating: 4.4,
    image: "/2025-10-15.jpg",
    description: "Hôtel moderne offrant des hébergements confortables avec un mélange de style contemporain et charme africain. Restaurant sur le toit avec vue sur la ville et chambres accessibles avec douches à l'italienne.",
    amenities: ["WiFi", "Restaurant sur le Toit", "Bar", "Piscine", "Salle de Sport", "Spa", "Centre d'Affaires", "Parking", "Service en chambre", "Installations Accessibles"],
  },
  {
    id: "nairobi-015",
    name: "Sarova Panafric Hotel",
    location: "Nairobi",
    price: 220,
    rating: 4.5,
    image: "/2026-01-28.jpg",
    description: "Hôtel emblématique de Nairobi avec jardins tropicaux lush et une riche histoire remontant à 1965. Chambres accessibles avec douches à l'italienne, à quelques minutes du centre-ville.",
    amenities: ["WiFi", "Piscine", "Restaurant", "Bar", "Jardin", "Installations de Conférence", "Parking", "Service en chambre", "Installations Accessibles"],
  },
  // ========== MAASAI MARA HOTELS ==========
  {
    id: "maasai-mara-001",
    name: "Mara Serena Safari Lodge",
    location: "Maasai Mara",
    price: 450,
    rating: 4.7,
    image: "/mara-1.jpg",
    description: "Lodge iconique perché sur une colline avec vue panoramique sur la Grande Migration. Safaris guidée inclus, cuisine gastronomique et expérience safari authentique.",
    amenities: ["WiFi", "Piscine", "Spa", "Restaurant", "Bar", "Safari", "Vue sur la Migration"],
  },
  {
    id: "maasai-mara-002",
    name: "Mara Intrepids Camp",
    location: "Maasai Mara",
    price: 380,
    rating: 4.5,
    image: "/mara-2.jpg",
    description: "Camp de luxe avec tentes spacieuses et terrasse privée. Safari en véhicule 4x4 avec guides expérimentés. Position idéale le long de la rivière Talek.",
    amenities: ["WiFi", "Restaurant", "Bar", "Safari 4x4", "Tentes de Luxe", "Terrasse Privée"],
  },
  {
    id: "maasai-mara-009",
    name: "Angama Mara",
    location: "Maasai Mara",
    price: 1250,
    rating: 4.9,
    image: "/angama-mara.jpg",
    description: "Perché sur l'escarpement d'Oloololo avec vue panoramique sur le Triangle de la Mara. Ce lodge primé dispose de 30 suites tentées avec murs de verre du sol au plafond, terrasses privées et service exceptionnel. Expérience de safari ultime.",
    amenities: ["Piscine à Infinity", "Spa", "Centre de Fitness", "Studio de Photographie", "Boutique", "Restaurant", "Bar", "Safaris en Montgolfière", "Expériences Culturelles Maasai", "Service de Majordome", "WiFi"],
  },
  {
    id: "maasai-mara-010",
    name: "Ashnil Mara Camp",
    location: "Maasai Mara",
    price: 420,
    rating: 4.6,
    image: "/unnamed (18).webp",
    description: "Camp de luxe situé le long de la rivière Talek dans la réserve privée de Maasai Mara. Excellent pour l'observation du gibier, accès à la rivière et fréquentations fréquentes de la faune directement depuis le camp.",
    amenities: ["WiFi", "Safaris", "Tous Repas Inclus", "Vue sur la Rivière", "Bar", "Randonnées dans la Brousse", "Photographie", "Guides"],
  },
  {
    id: "maasai-mara-011",
    name: "Soroi Mara Bush Camp",
    location: "Maasai Mara",
    price: 480,
    rating: 4.7,
    image: "/mbc_main-30 (1).webp",
    description: "Camp éco-responsable intime dans une zone concession privée de la Maasai Mara offrant des expériences authentiques, excellent encadrement et conception à faible impact.",
    amenities: ["Tout Inclus", "Safaris", "Randonnées", "Repas en Brousse", "Bar", "Éco-responsable", "Guides"],
  },
  {
    id: "maasai-mara-012",
    name: "Soroi Larsens Camp",
    location: "Maasai Mara",
    price: 520,
    rating: 4.8,
    image: "/2024-07-12.webp",
    description: "Camp de luxe tenté classique avec élégance intemporelle, service superb et position idéale pour assister aux traversées de la rivière lors de la Grande Migration.",
    amenities: ["Tout Inclus", "Safaris", "Montgolfière", "Gastronomie", "Spa", "Bar", "Guides"],
  },
  {
    id: "maasai-mara-013",
    name: "Soroi Private Wing",
    location: "Maasai Mara",
    price: 680,
    rating: 4.9,
    image: "/unnamed (35).webp",
    description: "Aile privée exclusive au sein du Mara Serena Safari Lodge offrant une intimité ultime, service personnalisé et vues panoramiques sur les plaines de la Mara.",
    amenities: ["Majordome Privé", "Tout Inclus", "Safaris", "Dîner Privé", "Soins Spa", "Piscine à Infinity", "WiFi"],
  },
  {
    id: "maasai-mara-014",
    name: "Mara Maisha",
    location: "Maasai Mara",
    price: 450,
    rating: 4.6,
    image: "/2025-12-10.webp",
    description: "Éco-lodge contemporain avec tentes élégantes, piscine à infinity avec vue sur la Mara, et excellent observation du gibier dans un cadre de concession privée.",
    amenities: ["WiFi", "Piscine à Infinity", "Safaris", "Randonnées", "Restaurant", "Bar", "Spa"],
  },
  {
    id: "maasai-mara-015",
    name: "Keekorok Lodge",
    location: "Maasai Mara",
    price: 340,
    rating: 4.4,
    image: "/BOB04192_HDR.webp",
    description: "Lodge classique de service complet situé à l'intérieur de la réserve nationale de Maasai Mara avec vue directe sur le point d'eau, piscine et safaris fiables.",
    amenities: ["WiFi", "Piscine", "Safaris", "Restaurant", "Bar", "Petit-déjeuner en Brousse", "Guides"],
  },
  // ========== AMBOSELI HOTELS ==========
  {
    id: "amboseli-001",
    name: "Ol Tukai Lodge Amboseli",
    location: "Amboseli",
    price: 420,
    rating: 4.8,
    image: "/pool-area.jpg",
    description: "Lodge de luxe avec vues imprenables sur le mont Kilimanjaro et expériences wildlife exceptionnelles. Position privilégiée au cœur du parc national d'Amboseli.",
    amenities: ["Safaris", "Restaurant", "Bar", "Piscine", "Photographie", "WiFi", "Spa", "Guides"],
  },
  {
    id: "amboseli-007",
    name: "Ol Donyo Lodge",
    location: "Amboseli",
    price: 980,
    rating: 4.9,
    image: "/ol-donyo-lodge.jpg",
    description: "Lodge spectaculaire dans les Chyulu Hills avec vues à couper le souffle sur le mont Kilimanjaro. Expérience safari exclusive avec piscines privées, safaris à cheval et lits d'étoiles pour dormir sous le ciel africain. Suites accessibles avec douches à l'italienne.",
    amenities: ["Piscines Privées", "Safaris à Cheval", "Lits d'Étoiles", "Gymnase", "Spa", "WiFi Gratuit", "Restaurant", "Bar", "Vues Kilimanjaro", "Safaris", "Randonnées", "Installations Accessibles"],
  },
  {
    id: "amboseli-008",
    name: "Praro Amboseli Camp",
    location: "Amboseli",
    price: 250,
    rating: 4.5,
    image: "/poraro-amboseli-tent-1.jpg",
    description: "Branche fière des Zebra Plains Mara Camps, Praro Amboseli Camp offre une expérience safari authentique avec hébergements accessibles et vue majestueuse sur le mont Kilimanjaro. Larges ouvertures de tente, douches à l'italienne avec barres de maintien.",
    amenities: ["Vues Kilimanjaro", "Restaurant", "Bar", "Safaris", "Randonnées", "Feu de Camp", "Boutique", "Parking", "Énergie Solaire", "WiFi (Zones Communes)", "Installations Accessibles", "Véhicules Safari Accessibles"],
  },
  {
    id: "amboseli-010",
    name: "Kibo Safari Camp",
    location: "Amboseli",
    price: 260,
    rating: 4.5,
    image: "/unnamed(7).jpg",
    description: "Partie de la prestigieuse Kibo Collection, cet hôtel boutique offre un service personnalisé, hébergements élégants et cadre de jardin tranquille. Entièrement accessible avec douches à l'italienne et larges portes.",
    amenities: ["WiFi", "Restaurant", "Bar", "Jardin", "Transferts Aéroport", "Service en chambre", "Installations de Conférence", "Parking", "Spa", "Installations Accessibles"],
  },
  // ========== NAKURU HOTELS ==========
  {
    id: "nakuru-003",
    name: "Lake Nakuru Lodge",
    location: "Lac Nakuru",
    price: 280,
    rating: 4.5,
    image: "/lake-nakuru.jpg",
    description: "Lodge avec vue sur le parc national du lac Nakuru. Point de vue idéal pour observer les flamants roses et les rhinocéros. Situation privilégiée près du lac alcalin.",
    amenities: ["WiFi", "Restaurant", "Bar", "Safari", "Observation des Oiseaux", "Vue sur le Lac"],
  },
  {
    id: "nakuru-004",
    name: "Sarova Whitesands Beach Resort",
    location: "Lac Nakuru",
    price: 320,
    rating: 4.6,
    image: "/whitesands.jpg",
    description: "Complexe hôtelier de luxe au bord du lac Nakuru avec plages privées et installations de loisirs complètes. Parfait pour les familles et les couples.",
    amenities: ["Piscine", "Spa", "Restaurant", "Bar", "Plage", "Activités Aquatiques", "Enfants"],
  },
  // ========== NAIVASHA HOTELS ==========
  {
    id: "naivasha-001",
    name: "Lake Naivasha Crescent Camp",
    location: "Naivasha",
    price: 320,
    rating: 4.7,
    image: "/cresentlake.avif",
    description: "Camp de luxe sur les rives du lac Naivasha avec vues magnifiques sur le lac et excellente observation de la faune. Atmosphère paisible au milieu de la nature.",
    amenities: ["WiFi", "Restaurant", "Bar", "Activités Lac", "Safaris", "Spa", "Salon", "Service en chambre"],
  },
  {
    id: "naivasha-002",
    name: "Naivasha Serena Camp",
    location: "Naivasha",
    price: 300,
    rating: 4.6,
    image: "/serenacamp.jpg",
    description: "Camp tout compris avec expérience safari authentique et hospitalité exceptionnelle. Repas inclus et safaris quotidiens dans la réserve nationale du lac Naivasha.",
    amenities: ["Repas Inclus", "Safaris", "Activités Lac", "Cheminée", "Bar", "Spa", "Photographie", "WiFi"],
  },
  {
    id: "naivasha-003",
    name: "Hells Gate Game Lodge",
    location: "Naivasha",
    price: 280,
    rating: 4.5,
    image: "/hellsgate.jpeg",
    description: "Lodge de safari près du parc national de Hell's Gate avec excellentes opportunités de safari et atmosphère accueillante. Accès facile aux activités de vélo et randonnée.",
    amenities: ["Restaurant", "Bar", "Safaris", "Randonnée", "Escalade", "Parking", "WiFi", "Service en chambre"],
  },
  {
    id: "naivasha-004",
    name: "Lake Naivasha Sopa Resort",
    location: "Naivasha",
    price: 280,
    rating: 4.5,
    image: "/2025-12-22.webp",
    description: "Complexe familial sur les rives du lac Naivasha avec beaux jardins, piscine et accès facile aux promenades en bateau, observation des oiseaux et parc national de Hell's Gate.",
    amenities: ["WiFi", "Piscine", "Restaurant", "Bar", "Promenades en Bateau", "Installations de Conférence", "Jardins"],
  },
  {
    id: "naivasha-005",
    name: "Lake Naivasha Simba Lodge",
    location: "Naivasha",
    price: 220,
    rating: 4.3,
    image: "/unnamed (61).webp",
    description: "Lodge confortable de moyenne catégorie avec proximité du lac, bonnes installations et base pratique pour Hell's Gate, Crescent Island et safaris en bateau.",
    amenities: ["WiFi", "Restaurant", "Bar", "Piscine", "Activités Lac", "Parking"],
  },
  {
    id: "naivasha-008",
    name: "Muthu Lake Naivasha Country Club",
    location: "Naivasha",
    price: 280,
    rating: 4.5,
    image: "/muthu-lake-naivasha.jpg",
    description: "Élégant country club au bord du lac Naivasha offrant un mélange parfait de charme colonial et confort moderne. Entouré de jardins lush avec vues magnifiques sur le lac. Entièrement accessible.",
    amenities: ["WiFi", "Piscine", "Restaurant", "Bar & Salon", "Court de Tennis", "Promenades en Bateau", "Observation des Oiseaux", "Jardins", "Installations de Conférence", "Parking", "Service en chambre", "Sécurité 24h", "Installations Accessibles"],
  },
  // ========== SAMBURU HOTELS ==========
  {
    id: "samburu-001",
    name: "Samburu Intrepids Tented Camp",
    location: "Samburu",
    price: 400,
    rating: 4.8,
    image: "/samburu-intrepids-luxury (5).jpg",
    description: "Lodge ultra-luxueux sur la rivière Ewaso Nyiro avec expériences safari exceptionnelles et service personnalisé. Position idéale pour observer le Special Five.",
    amenities: ["Tout Inclus", "Safaris", "Activités Rivière", "Spa", "Bar", "Gastronomie", "Photographie", "Guides"],
  },
  {
    id: "samburu-005",
    name: "Ashnil Samburu Camp",
    location: "Samburu",
    price: 280,
    rating: 4.3,
    image: "/ashnil-samburu-camp.jpg",
    description: "Lodge bien positionné avec excellent observation du gibier près de Buffalo Springs. Installations complètes et atmosphère paisible dans la réserve de Samburu.",
    amenities: ["Safaris", "Restaurant", "Bar", "Parking", "Service en chambre", "WiFi", "Photographie", "Guides"],
  },
  // ========== NANYUKI HOTELS ==========
  {
    id: "nanyuki-012",
    name: "Sweetwaters Tented Camp",
    location: "Nanyuki",
    price: 380,
    rating: 4.7,
    image: "/sweetwaters-tented-camp-main.jpg",
    description: "Camp de luxe situé dans la réserve privée d'Ol Pejeta, offrant une observation exceptionnelle de la faune avec un point d'eau privé et vues magnifiques sur le mont Kenya. Expérience magique au cœur de la wilderness.",
    amenities: ["WiFi", "Restaurant", "Bar", "Piscine", "Parking", "Service en chambre", "Sécurité 24h", "Terrasse d'Observation", "Boutique", "Service de Blanchisserie", "Spa", "Safaris", "Safaris de Nuit", "Visites du Sanctuaire de Chimpanzés"],
  },
  // ========== TSAVO WEST HOTELS ==========
  {
    id: "tsavo-west-007",
    name: "Finch Hattons",
    location: "Tsavo Ouest",
    price: 850,
    rating: 4.8,
    image: "/finch-hattons.jpg",
    description: "Oasis de luxe au cœur du parc national de Tsavo Ouest, situé autour d'une source naturelle qui attire une abondante faune. Suites tentées exquis, spa de classe mondiale et expériences gastronomiques exceptionnelles. Entièrement accessible avec douches à l'italienne.",
    amenities: ["Piscines Privées alimentées par Source", "Spa", "Court de Tennis", "Cave à Vin", "Service de Majordome", "Gymnase", "WiFi Gratuit", "Restaurant", "Bar", "Safaris", "Observation des Oiseaux", "Randonnées", "Installations Accessibles"],
  },
  // ========== NAIVASHA ADDITIONAL HOTELS ==========
  {
    id: "naivasha-006",
    name: "Lake Naivasha Resort",
    location: "Naivasha",
    price: 260,
    rating: 4.4,
    image: "/unnamed (71).webp",
    description: "Propriété moderne de type complexe hôtelier sur le lac Naivasha avec plusieurs options de restauration, piscine et accès facile aux promenades en bateau et observation des oiseaux.",
    amenities: ["WiFi", "Piscine", "Multiple Restaurants", "Bar", "Safaris en Bateau", "Salles de Conférence"],
  },
  {
    id: "naivasha-007",
    name: "Enashipai Resort & Spa",
    location: "Naivasha",
    price: 320,
    rating: 4.6,
    image: "/2025-05-21.webp",
    description: "Complexe de luxe sur les rives du lac Naivasha offrant des chambres élégantes, un spa complet, plusieurs options de restauration et excellentes installations pour la détente, les conférences et les activités lacustres. Chambres accessibles avec douches à l'italienne.",
    amenities: ["WiFi", "Piscines Multiples", "Spa Complet", "Several Restaurants", "Bar & Salon", "Activités Lac & Promenades en Bateau", "Installations de Conférence & Événements", "Centre de Fitness", "Jardins", "Installations Accessibles"],
  },
  // ========== NAKURU ADDITIONAL HOTELS ==========
  {
    id: "nakuru-005",
    name: "Hotel Panorama Resort",
    location: "Lac Nakuru",
    price: 210,
    rating: 4.3,
    image: "/hotel-panorama-resort.jpg",
    description: "Hôtel avec vues panoramiques et chambres confortables overlooking la ville de Nakuru. Vue sur les montagnes environnantes.",
    amenities: ["WiFi", "Restaurant", "Bar", "Vues", "Parking", "Service en chambre", "Jardin", "TV"],
  },
  {
    id: "nakuru-006",
    name: "The Lake Nakuru Flamingo Lodge",
    location: "Lac Nakuru",
    price: 240,
    rating: 4.4,
    image: "/welcome-to-lake-nakuru.jpg",
    description: "Lodge thématique sur la nature célébrant les fameux flamants roses de Nakuru avec hébergements confortables.",
    amenities: ["WiFi", "Restaurant", "Piscine", "Bar", "Jardin", "Parking", "Service en chambre", "TV"],
  },
  {
    id: "nakuru-007",
    name: "Lake Nakuru Lodge",
    location: "Lac Nakuru",
    price: 220,
    rating: 4.3,
    image: "/lake-nakuru-lodge (1).jpg",
    description: "Lodge dans les limites du parc national du lac Nakuru avec accès direct à la faune. Observation des flamants roses depuis le lodge.",
    amenities: ["WiFi", "Restaurant", "Bar", "Safaris", "Parking", "Service en chambre", "Jardin", "Guides"],
  },
  {
    id: "nakuru-008",
    name: "Rock Hyrax Hotel",
    location: "Lac Nakuru",
    price: 170,
    rating: 4.1,
    image: "/caption.jpg",
    description: "Hôtel confortable avec atmosphère chaleureuse et tarifs abordables. Centre-ville de Nakuru.",
    amenities: ["WiFi", "Restaurant", "Bar", "Parking", "Service en chambre", "TV", "Climatisation", "Jardin"],
  },
  {
    id: "nakuru-009",
    name: "Ziwa Bush Lodge",
    location: "Lac Nakuru",
    price: 150,
    rating: 4.0,
    image: "/private-lovely-large.jpg",
    description: "Hôtel économique offrant des chambres propres et services basiques mais de qualité. Good value.",
    amenities: ["WiFi", "Restaurant", "Bar", "Parking", "Service en chambre", "TV", "Climatisation"],
  },
  {
    id: "nakuru-010",
    name: "Lake Nakuru Sopa Lodge",
    location: "Lac Nakuru",
    price: 190,
    rating: 4.2,
    image: "/lake-nakuru-sopa-lodge (1).jpg",
    description: "Hôtel 3 étoiles avec excellentes installations et emplacement pratique. Vue sur les collines environnantes.",
    amenities: ["WiFi", "Restaurant", "Piscine", "Bar", "Jardin", "Parking", "Service en chambre", "TV"],
  },
  {
    id: "nakuru-011",
    name: "Punda Milias Nakuru Camp",
    location: "Lac Nakuru",
    price: 215,
    rating: 4.3,
    image: "/aerial-view-of-pundamilias.jpg",
    description: "Hôtel moderne 3 étoiles avec design thématique safari et installations de qualité. Proche du parc national.",
    amenities: ["WiFi", "Restaurant", "Piscine", "Bar", "Jardin", "Parking", "Service en chambre", "Gymnase"],
  },
  {
    id: "nakuru-012",
    name: "Sarova Lion Hill Game Lodge",
    location: "Lac Nakuru",
    price: 320,
    rating: 4.7,
    image: "/unnamed (1).webp",
    description: "Situé dans le parc national du lac Nakuru, ce lodge magnifique offre des vues à couper le souffle sur le lac et les flamants roses. Chambres accessibles avec douches à l'italienne et barres de maintien.",
    amenities: ["WiFi", "Piscine", "Restaurant", "Bar", "Safaris", "Spa", "Boutique", "Parking", "Installations Accessibles"],
  },
  {
    id: "nakuru-013",
    name: "Sarova Woodlands Hotel & Spa",
    location: "Lac Nakuru",
    price: 280,
    rating: 4.6,
    image: "/Sarova-Woodlands-Nakuru.webp",
    description: "Une retraite paisible au cœur de Nakuru, offrant des hébergements luxueux et un spa complet. Entièrement accessible avec douches à l'italienne et zones publiques accessibles.",
    amenities: ["WiFi", "Piscine", "Spa", "Restaurant", "Bar", "Installations de Conférence", "Parking", "Service en chambre", "Installations Accessibles"],
  },
  {
    id: "nakuru-014",
    name: "Lake Nakuru Sopa Lodge",
    location: "Lac Nakuru",
    price: 290,
    rating: 4.4,
    image: "/lake-nakuru-sopa-lodge (5).jpg",
    description: "Lodge bien situé près du parc national du lac Nakuru offrant des vues sur les flamants roses, chambres confortables et bonnes installations pour l'observation des oiseaux et les safaris.",
    amenities: ["WiFi", "Piscine", "Restaurant", "Bar", "Safaris", "Observation des Oiseaux"],
  },
  {
    id: "nakuru-015",
    name: "Lake Nakuru Lodge",
    location: "Lac Nakuru",
    price: 240,
    rating: 4.3,
    image: "/Lake Nakuru Lodge (35).webp",
    description: "Lodge confortable avec vue sur le lac Nakuru et accès facile aux activités safari. Base idéale pour explorer le parc national.",
    amenities: ["WiFi", "Restaurant", "Bar", "Safaris", "Parking", "Service en chambre"],
  },
  // ========== KISUMU HOTEL ==========
  {
    id: "kisumu-001",
    name: "Sarova Imperial Hotel",
    location: "Kisumu",
    price: 210,
    rating: 4.5,
    image: "/2023-01-24.webp",
    description: "Surplombant le lac Victoria, cet hôtel élégant offre des vues magnifiques sur le lac et des équipements modernes. Chambres accessibles avec douches à l'italienne, avec accès facile aux attractions de Kisumu.",
    amenities: ["WiFi", "Restaurant", "Bar", "Vues sur le Lac", "Installations de Conférence", "Parking", "Service en chambre", "Installations Accessibles"],
  },
  // ========== MOMBASA HOTEL ==========
  {
    id: "mombasa-001",
    name: "Sarova Whitesands Beach Resort & Spa",
    location: "Mombasa",
    price: 350,
    rating: 4.8,
    image: "/2026-03-09.webp",
    description: "Le principal complexe balnéaire de Mombasa, situé sur des kilomètres de sable blanc pristine le long de l'océan Indien. Entièrement accessible avec douches à l'italienne, barres de maintien, allées accessibles et fauteuils roulants de plage disponibles.",
    amenities: ["WiFi", "Piscines Multiples", "Spa", "Multiple Restaurants", "Bars", "Sports Aquatiques", "Club Enfants", "Parking", "Installations Accessibles", "Fauteuils Roulants de Plage"],
  },
];

export const faqsFR = [
  { question: "Quelle est la meilleure période pour un safari au Kenya?", answer: "La meilleure période est de juin à octobre pour la saison sèche et la Grande Migration. Janvier à février est aussi excellent avec moins de monde. Cependant, chaque destination a ses propres saisons optimales." },
  { question: "Ai-je besoin d'un visa pour le Kenya?", answer: "La plupart des visiteurs ont besoin d'un visa pour entrer au Kenya. Vous pouvez obtenir un e-visa via le portail d'immigration du Kenya en ligne, ou obtenir un visa à l'arrivée. Les exigences varient selon la nationalité." },
  { question: "Le paludisme est-il un problème au Kenya?", answer: "Le risque de paludisme varie selon le lieu et la saison. La plupart des destinations safari en altitude plus élevée présentent un risque plus faible. Consultez une clinique de santé voyage avant votre voyage." },
  { question: "Quelle faune puis-je voir au Kenya?", answer: "Le Kenya offre les Big Five (lion, léopard, éléphant, buffle, rhinocéros), la Grande Migration, des centaines d'espèces d'oiseaux et une diversité incroyable de faune sauvage." },
  { question: "Les safaris sont-ils adaptés aux familles?", answer: "Oui, de nombreux lodges proposent des activités pour enfants, des safaris adaptés aux familles et des services de garderie. Certains lodges ont des програмmes spéciaux pour les enfants." },
  { question: "Quel équipement dois-je emporter pour mon safari?", answer: "Emportez des vêtements neutres, des couches pour les températures variables, des chaussures de marche, un chapeau, un écran solaire, des jumelles et un appareil photo. Les sacs à dos souples sont recommandés." },
  { question: "Quelle est la politique d'annulation?", answer: "Les politiques d'annulation varient selon l'opérateur et la période. En général, l'annulation plus de 30 jours avant中得到 25% de frais, 15-30 jours得到 50%, moins de 15 jours得到 100%." },
  { question: "Le Kenya est-il sûr pour les touristes?", answer: "Le Kenya est généralement sûr pour les touristes dans les zones safari et touristiques établies. Nous recommandons de suivre les conseils de votre opérateur et d'éviter les zones non recommandées." },
];