// Spanish translations for destinations and hotels

export const locationsES = [
  {
    id: "nairobi",
    name: "Nairobi",
    slug: "nairobi",
    description: "La vibrante capital de Kenia – mejores hoteles de lujo, safaris en el Parque Nacional de Nairobi, Centro de Jirafas",
    image: "/Nairobi.avif",
    longDescription: "Nairobi, la capital animada de Kenia y puerta de entrada principal a los safaris del África Oriental, combina la energía urbana con experiencias de vida silvestre increíbles. Conocida mundialmente como la única capital con un parque nacional dentro de sus límites, Nairobi ofrece safaris en el Parque Nacional de Nairobi a solo 20 minutos del centro. Visite el famoso Centro de Jirafas, el Museo Karen Blixen, el Orfanato de Elefantes David Sheldrick, y el Museo Nacional de Nairobi. La ciudad cuenta con hoteles de lujo, lodges boutique, restaurantes en azoteas y excelente compras.",
    attractions: ["Safari en Parque Nacional de Nairobi", "Centro de Jirafas – Alimentar jirafas", "Orfanato de Elefantes y Rinocerontes", "Museo Karen Blixen", "Museo Nacional de Nairobi", "Bomas de Kenia – Espectáculo cultural"],
    bestTime: "Junio a octubre (temporada seca) y enero a febrero",
    updatedAt: new Date(),
  },
  {
    id: "maasai-mara",
    name: "Maasai Mara",
    slug: "maasai-mara",
    description: "La Gran Migración, los Big Cats y safaris en globo – el parque nacional más famoso de Kenia",
    image: "/maasai-mara.jpeg",
    longDescription: "Maasai Mara es el destino safari más emblemático de Kenia, mundialmente conocido por la Gran Migración anual donde más de 1,5 millones de ñus cruzan las llanuras de julio a octubre. El parque alberga una densa población de leones, leopardos, guepardos (Big Cats), elefantes, jirafas y cebras. Los lodges de lujo ofrecen vistas a las infinitas llanuras, y los safaris en globo al amanecer son una experiencia inolvidable.",
    attractions: ["Gran Migración (julio-octubre)", "Avistamiento de leones y leopardos", "Safari en globo", "Visitas a aldeas Maasai", "Game drives al amanecer", "Migración de ñus y cebras"],
    bestTime: "Julio a octubre para la migración, diciembre a marzo para los nacimientos",
    updatedAt: new Date(),
  },
  {
    id: "amboseli",
    name: "Amboseli",
    slug: "amboseli",
    description: "El reino de los elefantes con el Kilimanjaro de fondo – mejor lugar para ver elefantes",
    image: "/amboseli.jpeg",
    longDescription: "Amboseli es mundialmente conocido por sus impresionantes vistas del monte Kilimanjaro y sus grandes poblaciones de elefantes. El parque ofrece algunas de las mejores oportunidades de fotografía de vida silvestre en Kenia, con elefantes con grandes colmillos caminando frente al glaciar icónico del Kilimanjaro. Los humedales atraen cientos de aves y otros animales.",
    attractions: ["Vista del Kilimanjaro", "Avistamiento de elefantes", "Fotografía de vida silvestre", "Avistamiento de aves", "Safari en humedales", "Atardeceres espectaculares"],
    bestTime: "Octubre a marzo (vista más clara del Kilimanjaro)",
    updatedAt: new Date(),
  },
  {
    id: "tsavo-east",
    name: "Tsavo Este",
    slug: "tsavo-east",
    description: "El parque nacional más grande de Kenia con sus icónicos elefantes rojos",
    image: "/tsavo-east.jpg",
    longDescription: "Tsavo Este es el parque nacional más grande de Kenia, celebrado por sus elegantes elefantes rojizos que se bañan en el polvo rojo característico de la región. El parque ofrece safaris exclusivos lejos de las multitudes, con paisajes variados desde llanuras áridas hasta colinas rocosas.",
    attractions: ["Elefantes rojos de Tsavo", "Leones sin melena", "Safari exclusivo", "Paisajes variados", "Avistamiento de aves", "Lago Mudd"],
    bestTime: "Octubre a marzo (temporada seca)",
    updatedAt: new Date(),
  },
  {
    id: "tsavo-west",
    name: "Tsavo Oeste",
    slug: "tsavo-west",
    description: "Volcanes, aguas termales y la famosa Shetani Lava Flow",
    image: "/tsavo-west.jpg",
    longDescription: "Tsavo Oeste ofrece paisajes espectaculares con sus volcanes, aguas termales geotérmicas y la famosa corriente de lava Shetani. El parque alberga una gran variedad de fauna incluyendo elefantes, leones, jirafas y rinocerontes. El lago Chala en la frontera tanzana ofrece atardeceres magníficos.",
    attractions: ["Shetani Lava Flow", "Aguas termales", "Volcanes del parque", "Lago Chala", "Cavernas de Mzima", "Rinocerontes"],
    bestTime: "Octubre a marzo",
    updatedAt: new Date(),
  },
  {
    id: "samburu",
    name: "Samburu",
    slug: "samburu",
    description: "El Special Five – jirafa reticulada, cebra de Grévy, avestruz somalí, órice y gacela de Beisa",
    image: "/samburu.jpg",
    longDescription: "Samburu en el norte de Kenia ofrece una experiencia safari única con su Special Five: la jirafa reticulada, la cebra de Grévy, la avestruz somalí, el órice beisa y la gacela de Beisa. Los paisajes desérticos impresionantes y la cultura samburu auténtica complementan la experiencia.",
    attractions: ["Special Five", "Cultura samburu", "Paisajes desérticos", "Safari exclusivo", "Avistamiento de aves", "Río Ewaso Ng'iro"],
    bestTime: "Octubre a marzo",
    updatedAt: new Date(),
  },
  {
    id: "nakuru",
    name: "Lago Nakuru",
    slug: "nakuru",
    description: "Millones de flamencos y santuario de rinocerontes – parque pequeño pero rico",
    image: "/lake-nakuru.jpg",
    longDescription: "El Parque Nacional del Lago Nakuru es celebrado por sus millones de flamencos que crean un espectáculo rosa espectacular en el lago alcalino. El parque también es un santuario importante para los rinocerontes negros y blancos, con una de las mejores poblaciones de Kenia.",
    attractions: ["Flamencos", "Santuario de rinocerontes", "Avistamiento de aves", "Bosques de sodio", "Babuinos y monos", "Vista del Rift"],
    bestTime: "Octubre a marzo (temporada seca)",
    updatedAt: new Date(),
  },
  {
    id: "naivasha",
    name: "Lago Naivasha",
    slug: "naivasha",
    description: "Botes, hipopótamos y Crescent Island – escape relajante cerca de Nairobi",
    image: "/naivasha.jpg",
    longDescription: "El Lago Naivasha es uno de los lagos de agua dulce más hermosos de Kenia, ubicado a solo 90 minutos de Nairobi en el Valle del Rift. Famoso por safaris en bote donde puede acercarse a los hipopótamos, águilas pescadoras y cientos de especies de aves. Disfrute del ciclismo y game drives en el Parque Nacional de Hell's Gate.",
    attractions: ["Safari en bote en el lago", "Avistamiento de hipopótamos", "Hell's Gate – Ciclismo y senderismo", "Crescent Island – Safari a pie", "Crater Lake para flamencos", "Aguas termales"],
    bestTime: "Todo el año",
    updatedAt: new Date(),
  },
  {
    id: "meru",
    name: "Meru",
    slug: "meru",
    description: "Wildlife intacto – experiencia safari auténtica fuera de los caminos trillados",
    image: "/meru.jpg",
    longDescription: "Meru es una de las regiones safari más preservadas de Kenia, ofreciendo una experiencia auténtica lejos del turismo masivo. El Parque Nacional de Meru albergaba los últimos rinocerontes negros de Kenia en los años 80, y su población ha sido restaurada.",
    attractions: ["Wildlife preservado", "Rinocerontes negros", "Safari fuera de camino", "Sistemas fluviales", "Fotografía de caza", "Experiencia auténtica"],
    bestTime: "Octubre a marzo",
    updatedAt: new Date(),
  },
];

export const hotelsES = [
  {
    id: "nairobi-001",
    name: "Fairmont The Norfolk",
    location: "Nairobi",
    price: 350,
    rating: 4.8,
    image: "/nairobi-1.jpg",
    description: "Hotel legendario de Nairobi con elegancia colonial y estándares modernos. Ubicado en el corazón de la ciudad.",
  },
  {
    id: "nairobi-002",
    name: "Serena Hotel Nairobi",
    location: "Nairobi",
    price: 280,
    rating: 4.6,
    image: "/nairobi-2.jpg",
    description: "Hotel de lujo con vista al Parque Nacional de Nairobi. Piscina, spa y restaurantes gourmet.",
  },
  {
    id: "maasai-mara-001",
    name: "Mara Serena Safari Lodge",
    location: "Maasai Mara",
    price: 450,
    rating: 4.7,
    image: "/mara-1.jpg",
    description: "Lodge icónico con vista a la Gran Migración. Game drives incluidos, cocina gourmet.",
  },
  {
    id: "maasai-mara-002",
    name: "Mara Intrepids Camp",
    location: "Maasai Mara",
    price: 380,
    rating: 4.5,
    image: "/mara-2.jpg",
    description: "Campamento de lujo con tiendas espaciosas y terraza privada. Safari en vehículo 4x4.",
  },
  {
    id: "amboseli-001",
    name: "Tortilis Camp Amboseli",
    location: "Amboseli",
    price: 420,
    rating: 4.8,
    image: "/amboseli-1.jpg",
    description: "Campamento de lujo con vista directa al Kilimanjaro. Avistamiento de elefantes desde la piscina.",
  },
];

export const faqsES = [
  { question: "¿Cuál es la mejor época para un safari en Kenia?", answer: "La mejor época es de junio a octubre para la temporada seca y la Gran Migración. Enero a febrero también es excelente con menos gente." },
  { question: "¿Necesito visa para Kenia?", answer: "Sí, se requiere visa. Puede obtener una e-visa en línea antes de su viaje en el portal oficial del gobierno keniata." },
  { question: "¿Cuál es el presupuesto promedio para un safari?", answer: "Un safari de lujo suele costar 300-500 USD por persona por día, incluyendo alojamiento, comidas y safaris." },
  { question: "¿Es Kenia seguro para los turistas?", answer: "Kenia es generalmente seguro para los turistas en las zonas safari y turísticas. Recomendamos seguir los consejos de su operador." },
  { question: "¿Puedo reservar mi safari a última hora?", answer: "Es posible pero se recomienda reservar 2-3 meses con anticipación para garantizar disponibilidad, especialmente durante la temporada alta." },
  { question: "¿Qué animales puedo ver en Kenia?", answer: "Kenia ofrece los Big Five (león, leopardo, elefante, búfalo, rinoceronte), la Gran Migración, cientos de especies de aves y más." },
  { question: "¿Los safaris son adecuados para familias?", answer: "Sí, muchos lodges ofrecen actividades para niños y safaris adaptados para familias." },
  { question: "¿Debo llevar medicamentos contra la malaria?", answer: "Algunas zonas safari requieren profilaxis. Consulte a su médico y operador para consejos específicos." },
];